### ISSUE TITLE
Exception when cloning entity with mesh type particle system component

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#386] opened 2015-08-29 09:34 UTC
To repro:
* Load this pen
* After creation of the 'particles' entity, add the line:

    particles.clone();

You get the exception:

Uncaught TypeError: Cannot read property '0' of undefined

Seems that the mesh being cloned is expected to have a meshInstance array, which is undefined.

**Comment by Maksims** [comment] 2015-08-30 23:30
Duplicate of: https://github.com/playcanvas/engine/issues/315

**Closed by Maksims** 2015-08-30 23:30 UTC
Labels: bug
