### ISSUE TITLE
Remove need for custom gltf shader chunks

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#4484] opened 2022-07-28 11:47 UTC
The gltf parser currently overrides glossiness chunks in order to conform to gltf spec.

We need to support the gltf behaviour directly in standard-material instead. This way users will be able to create and edit GLTF materials in the editor.

**Comment by mvaligursky** [comment] 2022-07-31 08:28
duplicate of https://github.com/playcanvas/engine/issues/2404

**Closed** 2022-08-03 08:17 UTC
Labels: enhancement, area: gltf
