### ISSUE TITLE
M1 Mac, Monterey with Chrome Version 99.0.4844.51 (Official Build) (arm64) does not render 2k JPG right cubeface

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4091] opened 2022-03-08 12:26 UTC
Project: https://playcanvas.com/project/894195/overview/cubemap-bug-2048
Build: https://playcanv.as/p/9wGfJEGW/

On M1 Mac, Monterey with Chrome Version 99.0.4844.51 (Official Build) (arm64) does not render 2k JPG right cubeface

This is reproducible on multiple M1 Macs with Monterey installed

This grey area is meant to be a face of Bill Murrary 
<img width="930" alt="image" src="https://user-images.githubusercontent.com/16639049/157237421-9bfeecff-b748-42c7-af40-0b7b14c909c5.png">

What the cubemap should look like:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/16639049/157237557-1abe7178-a655-4a83-84e5-0e92d3511dd6.png">

Observations:  
- It only affects this right face
- It only affects JPGs that are 2048 x 2048 or larger. It doesn't matter which image we use. Using a PNG will work on the right face. Using 1024 x 1024 JPG or smaller will work
- The issue still occurs on Chrome Canary
- The color of the face does change with the image. It's almost as though its taking a pixel for the whole face
- Renders correctly in Safari and Firefox

**Comment by yaustar** [comment] 2022-03-08 13:18
Cannot reproduce with https://threejs.org/examples/?q=cubemap#webgl_materials_cubemap

**Comment by yaustar** [comment] 2022-03-08 13:35
Last working version of the engine was 1.30.0 (https://launch.playcanvas.com/1355954?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.30.0.js)

**Comment by willeastcott** [comment] 2022-03-08 13:49
Can you identify the offending commit specifically?

**Comment by yaustar** [comment] 2022-03-08 14:25
@willeastcott offending PR https://github.com/playcanvas/engine/pull/2216

Reverting cubemap.js in the PR makes the cubemap face appear: https://github.com/playcanvas/engine/pull/2216/files#diff-5cb4608464fb9cbde9200842fdedb8cc3d23c7aa71b111daceee4ed46de21458

**Comment by yaustar** [comment] 2022-03-08 14:50
If we force the format of the faces to be `PIXELFORMAT_R8_G8_B8_A8`, in the following code, it renders

```
const faces = new Texture(this._device, {
                    name: cubemapAsset.name + '_faces',
                    cubemap: true,
                    type: getType() || faceTextures[0].type,
                    width: faceTextures[0].width,
                    height: faceTextures[0].height,
                    format: faceTextures[0].format,
                    levels: faceLevels,
                    minFilter: assetData.hasOwnProperty('minFilter') ? assetData.minFilter : faceTextures[0].minFilter,
                    magFilter: assetData.hasOwnProperty('magFilter') ? assetData.magFilter : faceTextures[0].magFilter,
                    anisotropy: assetData.hasOwnProperty('anisotropy') ? assetData.anisotropy : 1,
                    addressU: ADDRESS_CLAMP_TO_EDGE,
                    addressV: ADDRESS_CLAMP_TO_EDGE,
                    fixCubemapSeams: !!assets[0]
                });
```

The reason why changing the right face of the cubemap to a PNG works is because it is `faceAssets[0]` and therefore it is used to set the format for the `faces` texture

**Comment by yaustar** [comment] 2022-03-08 16:10
None of the above explains why the initial issue happens though where a single face renders incorrectly. If all 6 faces were not rendering or if the smaller texture size also didn't render, I would make more sense.

**Comment by willeastcott** [comment] 2022-10-16 08:50
@mvaligursky Since Chrome has now reached v106, can you confirm the production browser no longer exhibits this issue? If so, please close this issue.

**Comment by mvaligursky** [comment] 2022-10-18 08:03
the issue is still present in Version 105.0.5195.102 (Official Build) (arm64)
but cannot be reproduced in Version 108.0.5315.0 (Official Build) canary (arm64)

**Comment by mvaligursky** [comment] 2022-10-18 08:05
the issue is also still present in Version 106.0.5249.103 (Official Build) (arm64)

**Comment by mvaligursky** [comment] 2023-05-30 16:25
works on Canary: Version 116.0.5801.0 (Official Build) canary (arm64)
but still not on the official version: Version 113.0.5672.126 (Official Build) (arm64)
which is strange, considering it worked on Canary 108.

**Comment by mvaligursky** [comment] 2024-03-01 16:30
I can no longer reproduce this on the same Mac, Chrome Version 122.0.6261.69 (Official Build) (arm64)

**Closed by mvaligursky** 2024-03-01 16:30 UTC
Labels: bug, area: graphics
