### ISSUE TITLE
All splat demos fail on FireFox desktop

### ISSUE THREAD

**Issue by pjbaron** [playcanvas/engine#5895] opened 2023-12-13 09:32 UTC
I mentioned this in the forums, raising it again here for visibility:
https://forum.playcanvas.com/t/gaussian-splatting-playcanvas/33503/39

Repro:
Start any demo in FireFox desktop browser.
e.g. https://launch.playcanvas.com/1917916?debug=true
Drag the screen to rotate the splat object.

Result:
The error will appear and sorting will stop.
![image](https://github.com/playcanvas/engine/assets/614817/0148769d-c812-46d7-8c7d-aa9fcd5ae512)

Expected Result:
No errors. Splats should be sorted by depth.

Environment:
Firefox Browser 120.0.1 (64-bit)
Windows 10 Pro 22H2 (patched today)
GTX 3080 Video Card
11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz   3.60 GHz

Please let me know if a stack trace or other information is needed.

**Comment by marklundin** [comment] 2023-12-13 12:04
Thanks @pjbaron. Just for reference I can't repro this on a Mac w/ FF 120. Did this not get solved as per [this suggestion](https://forum.playcanvas.com/t/gaussian-splatting-playcanvas/33503/50)?

**Comment by willeastcott** [comment] 2023-12-13 12:29
This is me on Win10:

![image](https://github.com/playcanvas/engine/assets/697563/960c1c06-3a33-4479-8c1a-77d5a63fa8e3)

**Comment by pjbaron** [comment] 2023-12-13 20:20
@marklundin unfortunately not. That suggestion fixed the depth sorting on _Chrome_ for me (The FF issue continues to be a blocker for any splat display in that browser, so I've jumped back to Chrome until it is fixed)

**Comment by marklundin** [comment] 2023-12-14 10:00
Hmm, that's strange. I can't seem to replicate. I have same CPU w/ v120.0.1 FF on Windows.

**Comment by willeastcott** [comment] 2023-12-14 13:33
@marklundin I had to keep rotating the shoe for about 30 seconds before the errors showed. Did you rotate for long enough?

**Comment by marklundin** [comment] 2023-12-14 13:38
Yep, was there for a few minutes. Is it fairly consistent in how often it errors?

**Comment by willeastcott** [comment] 2023-12-14 13:43
Hmm. I can't get it to error any more.

**Comment by mvaligursky** [comment] 2024-06-14 15:20
I could reproduce it before, but cannot at the moment, tested on FF 126 on MacOS. Possibly due to many improvements in our splat rendering in the last month. Closing for now, but please reopen if you can still reproduce this.

**Comment by Maksims** [comment] 2024-06-14 16:07
I have experienced that issue on mobile (Android).

**Comment by slimbuck** [comment] 2024-06-24 07:59
I believe #6357 might have addressed the underlying issue (which was updating the sort buffer in a `setTimeout` callback).

If you experience this issue again using up-to-date engine please post the details here.

**Closed** 2024-06-24 12:40 UTC
Labels: bug, area: graphics
