### ISSUE TITLE
Apple A12 (iPad, iOS) CubeMap Seams (IBL) bug

### ISSUE THREAD

**Issue by issacclee** [playcanvas/engine#1464] opened 2018-12-26 10:17 UTC
There is a bug with CubeMap Seams (IBL) on A12 and A12X chips (all new iPhone's and iPad's).  
Simple project that replicates it: https://playcanvas.com/project/594045/overview/cubemapissue  

# How it looks (wrong):
![iPad Pro A12X 1](https://i.imgur.com/i6xkp5E.jpg)
![iPad Pro A12X 2](https://i.imgur.com/f0ZApSO.jpg)

# How it should look:  
![PC 1](https://i.imgur.com/QmnsfR6.jpg)  
![PC 2](https://i.imgur.com/3QrWBeo.jpg)

**Comment by issacclee** [comment] 2018-12-26 10:54
Small update on the issue: on A12 chips `app.graphicsDevice.useTexCubeLod` is `true`, if only on them it is forced to `false` it makes a workaround.
So if engine could detect A12 chip to flip such switch, it will do the job for now.

**Comment by issacclee** [comment] 2018-12-26 11:19
Proposed PR: https://github.com/playcanvas/engine/pull/1465/files

**Comment by willeastcott** [comment] 2018-12-28 21:01
Hey @guycalledfrank - do you have any idea why the new iOS devices are exhibiting this behavior? The proposed workaround worries me a bit - what happens when A13 arrives etc?

**Comment by guycalledfrank** [comment] 2018-12-28 21:13
Well the proposed PR is what I suggested to Max who suggested it to author :D I tested it on 5S and didn't notice anything bad, so seems like a problem with newer models. I don't really know any elegant way to detect if cross-face cubemap interpolation is supported apart from literally drawing and reading back stuff. WebGL doesn't seem to define any strict rules about this behaviour.

**Comment by Maksims** [comment] 2019-01-02 09:03
Looks like `useTexCubeLod` flag was purely based on observation that devices with `extTextureLod` and less than 16 available textures per shader would support cubemap smooth seams. @guycalledfrank as mentioned there is no specific docs in WebGL specs about such behaviour, and seems like browser implementations don't expose any flags to probe it.
Which left it open to weird implementations by vendors - what exactly happening with A12 chip.
As this workaround does fixes this particular problem and makes all A12 chips render properly, I would assume it is working fix now without negative impacts, so worth merging.

If weird behaviours happen further, then proper manual test code have to be implemented, where it would render cubemap, and check on results as @guycalledfrank suggested. Reason @issacclee needs this fix, is that many their apps right now rendering wrong on new iPhones, and they rely on IBL a lot in their products.

**Comment by willeastcott** [comment] 2019-01-02 14:32
OK, thanks for your input @Maksims and @guycalledfrank. I'll merge this for now. But it will require a more comprehensive fix at some point...

**Comment by terence-wang** [comment] 2019-01-10 01:33
> Small update on the issue: on A12 chips `app.graphicsDevice.useTexCubeLod` is `true`, if only on them it is forced to `false` it makes a workaround.
> So if engine could detect A12 chip to flip such switch, it will do the job for now.

This solution still has problems, such as when there is a skybox in your scene, the system will throw a serious error

![image](https://user-images.githubusercontent.com/16871841/50940166-d3b77900-14ba-11e9-82a2-4addbcbc7613.png)

**Comment by Maksims** [comment] 2019-01-10 05:45
@terence-wang it has not been deployed to Editor yet.
And you sure it comes from this change? Do you have simple project to replicate an issue?

**Comment by terence-wang** [comment] 2019-01-10 06:31
> @terence-wang it has not been deployed to Editor yet.
> And you sure it comes from this change? Do you have simple project to replicate an issue?

I encountered this problem while using the engine development project. In the editor I mounted the script on the root and changed this property to make the problem appear.

[https://playcanvas.com/project/596015/overview/material-issue](https://playcanvas.com/project/596015/overview/material-issue)

**Comment by Maksims** [comment] 2019-01-11 06:51
I can confirm that issue happens with this fix too, but it is weird as on some scenes it is popping out, and on others it is not. So it is somewhat scene related. Looks like it did not initialise some textures for cubemap. Maybe it is not using `useTexCubeLod` flag everywhere properly, and in some places it does own logic ignoring the flag or something.

Basically, there needs to be a fix for A12 chips, and it seems like there is another logic that defines textures based on some other flag.

**Comment by Maksims** [comment] 2019-01-16 02:59
Tested it more.

@willeastcott you are right, it is because A12 chips degraded their WebGL support, and now reporting (webglreport.com) that only 8 texture units are supported in fragment shader. Making it very limited.
Another degradation of A12 is they removed cubemap seams filtering.  
Screw Apple :D

If `useTexCubeLod` is false, it will fallback to scenario where it uses separate textures for faces instead of cubemap, to emulate manual cubemap seams filtering. But that uses 6 out of available 8 textures. With one light with shadow on scene and one diffuse texture it is already barely fitting. If you add another texture to that material, A12 chip just will refuse to render it leading to error mentioned by @terence-wang.

Seems like best to revert such change, at least it will not throw errors, but IBL looks bad :(

If there is a way to do cubemap path but with fixed seams - that would fix everything. @guycalledfrank have to add on that.

**Comment by Maksims** [comment] 2019-01-16 07:55
Added a PR https://github.com/playcanvas/engine/pull/1473 with a fix suggested by @guycalledfrank

**Comment by lmx99** [comment] 2019-02-11 08:01
How is it going on? @Maksims your fix cause some weird problem , as the image 

![image](https://user-images.githubusercontent.com/12620520/52550927-316e1680-2e15-11e9-9630-9e1e9aece9de.png)

@willeastcott

**Comment by codebon77** [comment] 2019-05-30 14:37
This has hopefully been addressed in #1580.

**Closed** 2019-06-08 17:34 UTC
Labels: bug
