### ISSUE TITLE
Post effect scripts error when toggling camera component enabled state

### ISSUE THREAD

**Issue by lucaheft** [playcanvas/engine#5793] opened 2023-11-06 11:11 UTC
### Description

Post effects throw errors, when camera component is disabled and enabled again.
I only tested this with `posteffect-brightnesscontrast.js` but this propably applies to all post effects.

Error:
```
ASSERT FAILED:

Framebuffer creation failed with error code FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT, render target: Camera-posteffect-0

[object Object]

Shader [Shader Id 0 BrightnessContrastShader] requires texture sampler [uColorBuffer] which has not been set, while rendering [Pass:Postprocess | BrightnessContrastEffect | Pass:RenderPass-drawQuadWithShaderFramebuffer | drawQuadWithShader | QuadRender]
```

### Steps to Reproduce

1. Go to: https://playcanvas.com/project/1159639/overview/bug-post-effect-enabledisable
2. Press play
3. Disable camera component in editor
4. Enable camera component in editor
5. Post effect errors and gets stuck at current value

**Comment by mvaligursky** [comment] 2023-11-06 11:19
most likely a duplicate of https://github.com/playcanvas/engine/issues/4787 - see the workaround there.
I'll close this for now, but please reopen if this is not the same issue.

**Closed by mvaligursky** 2023-11-06 11:19 UTC
