### ISSUE TITLE
Weird texture .exr .hdr artifacts on IOS device

### ISSUE THREAD

**Issue by TrongHieu90** [playcanvas/engine#1930] opened 2020-03-23 15:21 UTC
The IOS test device is Iphone 8.

### Description
The texture shows some errornous banding artifacts on .exr lightmap texture. It is normal on Android device (Samsung s9) as well as desktop.

Tested on all popular browser (Firefox, Chrome, Safari on Iphone8), (Firefox, Chrome on Samsung S9)

It is normal on MAC pc.

It also happens with the official Orange Room project, which uses .hdr file for lightmap texture.

![5af6e00afc6502b42cb4aa04bac421eb4a6512e7_2_1035x582](https://user-images.githubusercontent.com/20443445/77332015-11b55b80-6d54-11ea-9e73-72ecb2095646.jpeg)

Topic on the forum with other user confirmation: 
https://forum.playcanvas.com/t/weird-texture-artifacts-when-open-with-ios-iphone-8/12374

### Steps to Reproduce

1. Use .exr, hdr file for lightmap texture
2. View the texture in IOS device

**Comment by slimbuck** [comment] 2020-05-19 17:23
I haven’t been able to repro on iPhone 7:

![54F1D4DF-C423-4FB6-8E42-8AE7273DADF2](https://user-images.githubusercontent.com/11276292/82357994-c3dc6d00-99fd-11ea-81bf-ac9d52d52bb5.png)

(Using the link in the forum post)

**Comment by slimbuck** [comment] 2020-05-19 17:24
(Though the orange room example does have lightmap banding on the same device)

**Comment by willeastcott** [comment] 2020-05-19 20:26
It's fine on iPhone XS with iOS 13.4.1 too:

![Image from iOS (34)](https://user-images.githubusercontent.com/697563/82374724-5dfcdf00-9a17-11ea-9c0b-324899816384.png)

**Comment by TrongHieu90** [comment] 2020-05-20 14:56
@slimbuck , @willeastcott 
Its fine now because I fixed it (by using a HDR plugin of Photoshop to compress the 32 bit.exr to 8 bit png file)

I found out that Iphone does not support WebGL 2 (on all of the browsers), which will lead to this issue. Even with dithering setting when baking the lightmap does not fix it.

The orange room sample by playcanvas will display this issue the clearest.

**Comment by slimbuck** [comment] 2020-06-12 09:02
Turns out the banding is due to the way safari handles alpha when loading png images. Safari on iOS applies 'premultiply alpha' to the texture at load time, which means multiplying the R, G and B channel by A. When the image is subsequently used as a texture, safari then appears to reverse this operation (dividing RGB by A) in order to return the image to roughly it's original state. However in the process the R, G, B channels loose bits compared to the original. Thus the banding.

I've created the following test to demonstrate the banding https://launch.playcanvas.com/936882.

**Comment by slimbuck** [comment] 2020-06-12 10:20
The reason this is an issue for lightmaps is that we convert 'high dynamic range' pixels (which can contain values > 1.0) to RGBM format. This format stores a multiplication factor in the PNG's alpha channel.

Another option is to convert lightmaps directly to RGB without storing a multiplication factor and effectively clamping lighting values to a maximum of 1.0. (This is what @TrongHieu90 has done in the example scene). In this case there will be no banding on iOS, because premultiplying with an alpha value of 1.0 leaves the data unchanged.

**Comment by slimbuck** [comment] 2020-06-12 10:51
This bug has been logged on webkit already https://bugs.webkit.org/show_bug.cgi?id=138477.

**Comment by Maksims** [comment] 2021-03-05 16:57
Bug has not been updated since 2014. This affects many of my clients, and it would be great to find either alternative to PNG for RGBM or other way to store HDR lightmap data, or provide more testing and details to bug report, so that they can resurrect efforts on fixing it.

**Comment by willeastcott** [comment] 2021-03-05 17:27
Basis?

**Comment by Maksims** [comment] 2021-03-05 18:00
> Basis?

Currently it is not available for RGBM texture, nor there is a way in Editor to upload HDR texture and use basis only path.

Also ThreeJS had to solve this:
https://github.com/mrdoob/three.js/pull/21145

**Comment by mvaligursky** [comment] 2021-03-05 18:14
maybe we could use
https://github.com/playcanvas/engine/issues/2418
or 
https://github.com/playcanvas/engine/issues/1408

**Comment by Maksims** [comment] 2021-03-05 18:59
Just as a reminder, here is an example of what is being talked, and how severe it is:
![image](https://user-images.githubusercontent.com/636263/110161020-7480f500-7df5-11eb-8e36-b056c81f2a44.png)

We're doing a workaround on one project: have two assets, one with RGB and another greyscale with Alpha in it, and then create RGBA8 texture and upload it. But it is done on load times, and not great for bandwidth and cpu parsing.

**Comment by marklundin** [comment] 2021-07-13 10:30
Has anyone tried compressing the lightmaps with Basis? Theoretically, this should work, right?

**Comment by Maksims** [comment] 2021-07-13 14:24
> Has anyone tried compressing the lightmaps with Basis? Theoretically, this should work, right?

It won't work.
RGBM is very specific of the relationship between RGB and A (M), channels, and if there is any compression that shifts colors, it will create bandings and other artifacts straight away. So compressing RGBM as is - won't work.
An alternative could be looking for alternative compressed formats that allow storing HDR data, if such exist, then this could be an alternative path.

What many have to do, to get around this - is to store RGB and A (as RGB) in two separate PNG files. And then combine in runtime.

**Comment by slimbuck** [comment] 2021-07-13 14:57
@marklundin ASTC basis files should work fine, but will likely be quite big compared to equivalent PNG. Whereas the ETC basis files will be small but suffer from the artifacts @Maksims mentions.

**Comment by marklundin** [comment] 2021-07-13 15:43
Hmm fair point. Does anyone know the status of AVIF for safari? I can't find the ticket, but my understanding was that it was there but not enabled as yet. This is HDR correct?

**Comment by mvaligursky** [comment] 2021-07-13 15:45
AVIF ticket. https://github.com/playcanvas/engine/issues/2418
it's HDR but only 10 bites I think ..

**Comment by mvaligursky** [comment] 2021-07-13 15:53
In the past I had issue with banding then storing larger range lightmaps, like we do here: 0..8. I ended up storing range 0..3 or 0..4 (not sure, but it was acceptable range) and that pretty much removed the banding. Maybe we could try something like that here as well. Don't store anything in the alpha channel, but allow 0..3 range to be stored as 0..255 in the texture, and multiply it by 3 in the shader.

**Comment by marklundin** [comment] 2021-08-20 08:31
We're trying to figure out a workaround for IOS in a current project as the lightmaps look truly terrible at the moment. I think for the time being, a flatter LDR version is preferable to the banding, so we're running through all the lightmaps and converting them so we have a set for IOS and a set for everything else.

I'm not totally sure how the range is encoded, but what would be the conversion function that would translate one of the existing lightmaps into a one that we could load for IOS so that `HDR(r, g, b, a) => LDR(r, g, b, 1)` if that makes any sene 😆

**Comment by mvaligursky** [comment] 2021-08-20 08:38
HDR lightmaps are stored in the RGBM format, and this is the function we use to decode it back to linear space:
https://github.com/playcanvas/engine/blob/957f7176e49d2894d26aa9a3090c6ad864c64142/src/graphics/program-lib/chunks/reproject.frag#L55-L58

Note that this give you values in larger range than 0..1 (should be 0..8), so you'd need to handle it .. maybe by clamping, or scaling the range? In the past I stored 0..3 or similar range in the LDR texture, and had a fixed multiplier in the shader to bring it to full 0..8 range.

**Comment by mvaligursky** [comment] 2021-08-20 10:30
@marklundin - see the linked PR above for a possible workaround solution by @slimbuck

**Comment by marklundin** [comment] 2021-08-20 12:02
Thanks chaps! Super helpful as always! So this basically adds a JS decoder that avoid the native Safari version? Do you know if there's any performance overhead with this?

**Comment by slimbuck** [comment] 2021-08-20 13:10
This version should be worse in a number of ways:
- it's an additional script adding to download size
- probably decodes slower than the built-in browser png decode
- runs on the main thread

I actually tried to reproduce banding on my iphone 7 device but didn't manage. Which version of iOS/Safari are you seeing banding?

**Comment by Maksims** [comment] 2021-08-20 15:24
iPhone 7 Plus, in Safari has this issue.

**Comment by marklundin** [comment] 2021-08-20 15:30
Latest IPad Pro/iPad/IPhone. I've not done a full test across iOS devices as I saw this was a long standing WebKit issues so assumed it was across most devices.

The additional script is ok in our case as we have a high load anyway. the decode perf might be an issue as we're already doing mesh decompression, but I'd need to test this

**Comment by slimbuck** [comment] 2021-08-20 15:57
> iPhone 7 Plus, in Safari has this issue.
> Tons of iOS devices had this issue for years now.

Seems I was using the wrong lightmap. I've updated #3419 to clearly show the banding.

**Comment by willeastcott** [comment] 2022-10-15 23:18
The original [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=138477) has now been resolved. Here's 'Orange Room' running on my iPhone XS:

![IMG_0787](https://user-images.githubusercontent.com/697563/196010826-45246ff4-fb8a-43b4-bf98-2ac1e1ef9df9.PNG)

Note that older devices (e.g. iPhone 6 and lower) will not get this fix.

However, I am closing this issue as this is now greatly mitigated.

**Closed by willeastcott** 2022-10-15 23:18 UTC
Labels: bug, area: graphics
