### ISSUE TITLE
Add option to  set size of shadow map frustum based on bounding boxes of shadow casters.

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#4812] opened 2022-11-01 17:30 UTC
Right now, size of shadow map frustum does not depend on size of objects that cast shadows. So, it is hard to achieve high quality of shadows for small objects. It would be great to have an option to keep frustum as small as possible depending on size of objects that cast shadows.

**Comment by mvaligursky** [comment] 2022-11-01 17:39
duplicate of https://github.com/playcanvas/engine/issues/813, unless I'm mistaken.

**Closed by mvaligursky** 2022-11-01 17:39 UTC
Labels: feature request, area: graphics

**Comment by querielo** [comment] 2022-11-01 18:41
> duplicate of #813, unless I'm mistaken.

You are right. Thanks!
