### ISSUE TITLE
 There is a problem opening gltf preview in the mobile browser

### ISSUE THREAD

**Issue by wei292224644** [playcanvas/engine#3614] opened 2021-10-25 09:19 UTC
https://user-images.githubusercontent.com/16398073/138668713-b5986b23-9ed9-49f4-8bc4-5d3879b6e2ce.mp4

In safari, when I retired safari to the background while refreshing and waited for gltf to load, I switched back to safari. In this way, hdr will load abnormally, and reflection will also have problems.

I don’t know why, I see hdr loading seems to be normal.

**Comment by yaustar** [comment] 2022-01-11 16:50
@wei292224644 Are you still running into this issue? I've been unable to reproduce this on iOS 14 and 15. 

Closing for now but please reopen if this is still an issue

**Closed by yaustar** 2022-01-11 16:50 UTC
Labels: bug, area: graphics, area: gltf
