### ISSUE TITLE
Shader throws [.WebGL-0x7fccc403c000]GL ERROR :GL_INVALID_OPERATION warning

### ISSUE THREAD

**Issue by PHou81** [playcanvas/engine#1778] opened 2019-12-13 12:34 UTC
As discussed here: https://forum.playcanvas.com/t/matcap-in-playcanvas/11574

A seemingly simple demo scene is throwing `[.WebGL-0x7fccc403c000]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.`

The shader is very simple and there doesn't seem to be an obvious reason for this warning. 
Direct link to the demo project:
https://playcanvas.com/project/575970/overview/matcap-shaders

The issue is seen on both MacOS 10.14.6 in Chrome and Firefox as well as Windows 10 in Chrome.

**Comment by Maksims** [comment] 2019-12-13 13:21
In this example, you do not render anywhere into texture?
This is usually due to OpenGL limitation of reading and writing to the same texture during same draw call.

**Comment by PHou81** [comment] 2019-12-13 13:22
No, it's just manipulating the normals as far as I can tell.

**Comment by PHou81** [comment] 2020-01-01 23:20
It appears that the warning has something to do with how realtime shadows are rendered.
 
I just discovered that if I turn off shadows on the model and instead enable them in code with a delay to make sure that shadows are rendered after the custom material has been applied, the warning is no longer logged in the console.

If I enable shadows first, the warning is logged as soon as the custom material is applied.

**Comment by slimbuck** [comment] 2020-01-02 08:43
The errors generated on Safari are due to having WebGL 2.0 experimental feature enabled. Please disable this as Safari support for WebGL 2.0 is incomplete.

**Comment by willeastcott** [comment] 2020-02-07 17:57
Closing this because we suspect the warning is caused by an incomplete WebGL 2 implementation in iOS Safari. Please reopen if you believe we have reached the wrong conclusion.

**Closed by willeastcott** 2020-02-07 17:57 UTC
