### ISSUE TITLE
Depth-related issues in Area Lights demo, WebGPU only

### ISSUE THREAD

**Issue by cognitiveplus** [playcanvas/engine#6338] opened 2024-05-04 12:10 UTC
Depth-related issues in [Area Lights](https://playcanvas.github.io/#/graphics/area-lights) demo.
Macbook Air M1, Chrome
WebGPU only
Ventura 13.4

Video: https://github.com/playcanvas/engine/assets/5297578/c7b3e761-3bde-4c7b-92ec-0f4ad4270b5c

<img width="1280" alt="Screenshot 2024-05-04 at 15 59 44" src="https://github.com/playcanvas/engine/assets/5297578/5560c6cb-542e-4358-94e0-b57527328cd0">

**Comment by mvaligursky** [comment] 2024-05-07 07:50
duplicate of https://github.com/playcanvas/engine/issues/5885

**Closed by mvaligursky** 2024-05-07 07:50 UTC
