### ISSUE TITLE
Allow collision component to accept mesh instances

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4828] opened 2022-11-08 11:08 UTC
Sometimes we generate a collision mesh on the fly, or get the mesh instance from elsewhere. It would be useful, if we could feed the instance directly to the collision component to create a collision mesh. At the same time, making a material optional when creating a new mesh instance, since it is not used for rendering.

**Comment by mvaligursky** [comment] 2022-11-08 11:19
duplicate of https://github.com/playcanvas/engine/issues/4181

**Closed by mvaligursky** 2022-11-08 11:19 UTC
Labels: feature request, area: physics
