### ISSUE TITLE
Script initialize() can be triggered twice

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#232] opened 2015-04-15 14:39 UTC
If an Entity is disabled at runtime but is enabled in the initialize() method of a script that runs before it in the hierarchy. It will be initialized twice. Once in onEnable, and once in the normal initialize phase.

**Comment by Maksims** [comment] 2015-08-10 16:25
Duplicate of #359

**Closed by Maksims** 2015-08-10 16:25 UTC
Labels: bug

**Comment by SquareLi** [comment] 2015-09-15 15:18
It also happens when entity is disabled in Editor.
