### ISSUE TITLE
activeStateProgress does not return 1 at the end when speed is greater than 1

### ISSUE THREAD

**Issue by ertugrulcetin** [playcanvas/engine#4904] opened 2022-12-02 11:28 UTC
I’ve noticed that AnimComponent’s activeStateProgress does not return 1 at the end when the speed is greater than 1.

I have an animation with a duration of 4.5 secs when the animation speed is 1 and I run activeStateProgress regularly and at the end, I get the result 1. But when I update the animation’s speed to for example 3, I get 0.26 at the end.

Also I have a suggestion that might work for `_getActiveStateProgressForTime`;

```
const activeClip = this._animEvaluator.findClip(this.activeStateAnimations[0].name);
if (activeClip) {
    const speed = this.activeStateAnimations[0].speed;
    return (time * speed) / activeClip.track.duration;
}
```

**Comment by yaustar** [comment] 2022-12-02 11:30
Duplicate of https://github.com/playcanvas/engine/issues/4903

**Closed** 2022-12-02 11:29 UTC
