### ISSUE TITLE
I set material.useGammaTonemap = true in my model,but seems like it dose't work

### ISSUE THREAD

**Issue by qiansanwansan** [playcanvas/engine#2357] opened 2020-08-17 08:46 UTC
I download a FBX model from the editor. After downloading, it contains the corresponding JSON files and images. I use this method to load the model. My code is as follows:
```
var url = "../FYPlaycanvas/paint_whit/paint_whit.json";
        app.assets.loadFromUrl(url, "model", function (err, asset) {
            self.car = new pc.Entity();
            self.car.addComponent("model", {
                type: "asset",
                asset: -10,
                castShadows: true,
                isStatic: false,
                castShadowsLightmap: true,
                receiveShadows: true,
                lightmapped: false
            });
            app.root.addChild(self.car);
        });
```
but the effect is different from that of using the editor.To figure this problem,I compared all the parameters
,but they are same.so I changed my ways,  In the Editor,I repeated the problem:the key point is material.useGammaTonemap.

In the Editor,
If material.useGammaTonemap = true,the effect is right,screenshot is here:
![normal](https://user-images.githubusercontent.com/18042499/90376920-cb1d2080-e0a9-11ea-8c40-1fbafe295258.png)

If material.useGammaTonemap = false,the effect is wrong,which is same as I used with engine'effect,screenshot is here:
![unnormal](https://user-images.githubusercontent.com/18042499/90377561-b8efb200-e0aa-11ea-99f4-bcd43b81861a.png)

but my log shows I set it true.so it seems material.useGammaTonemap = true dose't work,I don't know why,please help.

**Comment by willeastcott** [comment] 2021-12-26 18:54
I have a suspicion that this is because your Editor scene has [Gamma](https://developer.playcanvas.com/en/user-manual/designer/settings/#gamma-correction) set to 2.2:

![image](https://user-images.githubusercontent.com/697563/147417441-5b9fb58a-81df-44eb-8c41-21fe9a734572.png)

However, your 'Engine-only' app needs to enable this explicitly like this:

```
app.scene.gammaCorrection = pc.GAMMA_SRGB;
```

I'm fairly certain this is what the problem is, so I will close this issue for now. But if you disagree, please follow up and I will reopen it.

**Closed by willeastcott** 2021-12-26 18:54 UTC
Labels: bug
