### ISSUE TITLE
TypeError: this.canvas.getBoundingClientRect is not a function problem

### ISSUE THREAD

**Issue by Thanh9356** [playcanvas/engine#1714] opened 2019-10-15 14:58 UTC
I'm using PlayCanvas 1.24.0-dev, Firefox browser
This is my error when I test samples:
```
TypeError: this.canvas.getBoundingClientRect is not a function playcanvas.js:5089:35
    updateClientRect playcanvas.js:5089
    GraphicsDevice playcanvas.js:4607
    Application playcanvas.js:22962
```
P/S: Chome browser is not working with the same error

**Comment by willeastcott** [comment] 2019-10-15 17:37
I can't reproduce this in FF 69.0.3 on Windows 10.

**Comment by Thanh9356** [comment] 2019-10-16 08:27
> 
> 
> What hardware and OS is this?

Intel Core 2 Duo
32-bit Windows 7
Firefox 70.0b14 (Developer Editon)

**Comment by willeastcott** [comment] 2019-10-16 08:59
I simply can't reproduce this problem:

![image](https://user-images.githubusercontent.com/697563/66904119-79c08280-effb-11e9-88f6-fa19e5711a2b.png)

Do you get the same problem if you run a PlayCanvas game, such as:

https://playcanv.as/p/2OlkUaxF/

**Comment by Thanh9356** [comment] 2019-10-16 11:47
> I simply can't reproduce this problem:
> 
> ![image](https://user-images.githubusercontent.com/697563/66904119-79c08280-effb-11e9-88f6-fa19e5711a2b.png)
> 
> Do you get the same problem if you run a PlayCanvas game, such as:
> 
> https://playcanv.as/p/2OlkUaxF/

No, it worked well. Game can load without any problem

**Comment by willeastcott** [comment] 2019-10-16 13:17
What happens if you open the JS console and do this:

![image](https://user-images.githubusercontent.com/697563/66922808-b4d4ad00-f01f-11e9-935f-2a98912e7717.png)

**Comment by Thanh9356** [comment] 2019-10-16 14:06
![ảnh](https://user-images.githubusercontent.com/36446935/66926695-afe01f80-f058-11e9-9dcf-8f4e52bf681e.png)
That's just like that

**Comment by willeastcott** [comment] 2019-10-16 15:39
Do you know how to use the debugger? Check 'Pause on exceptions' and then inspect the value of this.canvas. What do you see? Does it look like a valid canvas object?

![image](https://user-images.githubusercontent.com/697563/66935157-852fa000-f033-11e9-9992-23d6e6291ee3.png)

**Comment by Thanh9356** [comment] 2019-10-17 01:26
Yep... it's correct. It's a vaild object

**Comment by willeastcott** [comment] 2019-10-17 08:50
Can you investigate further then? Is it a valid canvas object? Does it have getBoundingClientRect in the prototype chain?

**Comment by Thanh9356** [comment] 2019-10-19 07:18
![ảnh](https://user-images.githubusercontent.com/36446935/67139494-252b3a80-f27b-11e9-957a-acc2d8c0fcfb.png)
Can you check my code pls? I don't know what did you say

**Comment by kungfooman** [comment] 2019-10-19 07:38
Put your code in `window.onload` or `load` even listener, the `<canvas>` probably doesn't exist at the moment you execute that script (e.g. in `<head>`)

```
	window.addEventListener("load", function(event) {
		// var app = ...
	});
```

**Comment by Thanh9356** [comment] 2019-10-26 09:44
> Put your code in `window.onload` or `load` event listener, the `<canvas>` probably doesn't exist at the moment you execute that script (e.g. in `<head>`)
> 
> ```
> 	window.addEventListener("load", function(event) {
> 		// var app = ...
> 	});
> ```

What about making the ```<script>``` in ```<body>```?

**Comment by kungfooman** [comment] 2019-10-26 11:27
Works too, but I prefer to make my JS/TS code independent from whatever is in your HTML files. Doesn't matter then if you spawn one instance or ten, everything is nicely encapsulated:

```ts
export class Whatever {
	canvas: HTMLCanvasElement;
	app: pc.Application;

	constructor() {
		var canvas = <HTMLCanvasElement> document.createElement("canvas");
		this.app = new pc.Application(canvas, {
			mouse: new pc.Mouse(canvas),
			keyboard: new pc.Keyboard(window),
			touch: new pc.TouchDevice(document.body),
			elementInput: new pc.ElementInput(canvas),
			vr: true
		});
		document.body.appendChild(canvas);
		canvas.focus(); // focus the canvas for keyboard input
		this.app.start();
		this.canvas = canvas;
		this.app.root.name = "root";
		// ...
	}
}

window.addEventListener("load", function(event) {
    var whateverA = new Whatever();
    var whateverB = new Whatever();
    Object.assign(window, {
        whateverA,
        whateverB
    })
});
```

**Comment by willeastcott** [comment] 2019-10-27 09:55
Closing this because it looks like a bug in the reporter's code.

**Closed by willeastcott** 2019-10-27 09:55 UTC
Labels: bug
