### ISSUE TITLE
Button element with Sprite Change, opacity change bug.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#2138] opened 2020-06-06 09:31 UTC
1. Open Editor
2. Launch
3. Click on button few times

Issue: infinite loop somewhere in engine.

https://playcanvas.com/project/692465/overview/button-sprite-change-click-bug

**Comment by jpauloruschel** [comment] 2022-01-04 16:07
Hello!
I don't have access to this project (or it was deleted since this bug was opened some time ago), but it seems like this issue was fixed with:
- https://github.com/playcanvas/engine/pull/3817
- https://github.com/playcanvas/engine/pull/3821

Closing this issue as I couldn't reproduce with an Engine release after these fixes (https://github.com/playcanvas/engine/releases/tag/v1.51.1 or later). Please re-open this issue if it persists.

**Closed by jpauloruschel** 2022-01-04 16:07 UTC
Labels: area: ui
