### ISSUE TITLE
Post effects on multiple viewport rendering

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#4946] opened 2022-12-21 09:04 UTC
Post effects applied to cameras that have a different rect than the default break rendering (camera viewport with post effect applied has wrong resolution):

![image](https://user-images.githubusercontent.com/29543178/208863556-b14595ca-b252-40cd-99f4-33f7c0b3c3e9.png)

### Steps to Reproduce

1. Fork the Multiple Viewport Rendering example project
2. Attach a post effect to either of the cameras

The following issue seems related, though checking the engine source code it seems that rect is taken into consideration correctly for each post effect render target: https://github.com/playcanvas/engine/issues/3090

Stepping with the debugger while rendering and debugging the drawFullscreenQuat() method, something seems miscalculated there:
https://github.com/playcanvas/engine/blob/96141aad3a19b4d3744a14c4f5198f4416a018d2/src/scene/graphics/post-effect.js#L108

For some reason the values reported at the last draw of the effect (draw on the backbuffer) appear to apply the rect twice.

**Comment by mvaligursky** [comment] 2023-01-01 10:27
duplicate of https://github.com/playcanvas/engine/issues/2940

**Closed by mvaligursky** 2023-01-01 10:27 UTC
Labels: bug, area: graphics
