### ISSUE TITLE
Asset url resolution fails

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6694] opened 2024-06-13 09:04 UTC
The issue is similar to the previous one, where the module failed to resolve, when app was not served from root.

This time, the issue happens with the `asset.getFileUrl()`, which resolves differently when served from non-root self-hosting.

This is how the URL returned by `asset.getFileUrl()` looks like when app is on PlayCanvas:
![image](https://github.com/playcanvas/engine/assets/5677782/76527328-23b5-4d89-83dc-e86ac9115875)

And this is when self-hosted:
![image](https://github.com/playcanvas/engine/assets/5677782/1186776e-c85a-4175-a789-92446171de41)

This is because the `getFileUrl` method is adding an asset prefix:
![image](https://github.com/playcanvas/engine/assets/5677782/6ca176a1-6a91-4e51-847c-3be411e16359)

Which is an empty string after we download the app via Rest API:
![image](https://github.com/playcanvas/engine/assets/5677782/de7ba835-4208-407b-9c9e-9bd36c517dde)

Repro:

On PlayCanvas (works):
https://playcanvas.com/project/1228085/overview/asset-url-issue

Self-host (breaks):
[app.zip](https://github.com/user-attachments/files/15816698/app.zip)

```
npm install
node app.mjs
```
```
localhost:3000/printer
```

![image](https://github.com/playcanvas/engine/assets/5677782/81885bec-5792-4bdb-bbb2-3b24f6dbfe35)

**Comment by marklundin** [comment] 2024-06-13 15:54
`getFileUrl ()` will only return a path relative to the root of your project. It's unaware of your hosting directories, so you'd have to manually set that based on the context.

Having said that, if your `import()` is called from within an ESM Script, and is not an expression (ie. not using `getFileURL()`) then it should resolve in both launcher and published app

**Comment by LeXXik** [comment] 2024-06-13 16:18
Hmm, `getFileUrl()` doesn't need to be aware of the domain or path. It just depends on whatever is set in the registry prefix:

https://github.com/playcanvas/engine/blob/1806a1552779cd895dcfb2467dac817f7895c093/src/framework/asset/asset.js#L452

However, I think the settings file that is generated by builder can handle it. It can automatically resolve it:

![image](https://github.com/playcanvas/engine/assets/5677782/fdd519fd-4eea-43f0-9c2d-7e383c017ca1)

Instead of an empty string it could be `window.location.href`. We can patch it by post processing, of course, but it seems like its a PlayCanvas side issue. The build produced by the builder doesn't work as is. The behavior is different from when it is run on PC servers which add an URL prefix.

**Comment by marklundin** [comment] 2024-06-13 16:28
Looks like a duplicate of https://github.com/playcanvas/engine/issues/2364

**Comment by LeXXik** [comment] 2024-06-13 16:53
Ah, you are right. Closing as duplicate #2364

**Closed** 2024-06-13 16:54 UTC
