### ISSUE TITLE
Debug: Render collision  shape

### ISSUE THREAD

**Issue by derickwelman** [playcanvas/engine#1300] opened 2018-08-15 12:55 UTC
### Feature request
I was trying to add a collider for my GLB model, but I have not been able to fit it into the model in any way, it always seems to be inverted, out of scale, among other problems.
It would be much easier and agile to render and see exactly the shape of the colliders - both mesh and primitive types - during development.

**Comment by mast4461** [comment] 2019-08-28 07:05
As of today, I can see the shapes of collision components in the editor.

![image](https://user-images.githubusercontent.com/3101405/63833139-9bde4280-c972-11e9-830d-d4ff4ba18f69.png)
Is this what you wanted, @derickwelman?

**Comment by willeastcott** [comment] 2019-08-28 10:12
@mast4461 I think the problem is that you can only view GLB based models in the launch page and not the Editor but you can only view collision volumes in the Editor and not the launch page.

We are working on adopting GLB in the Editor properly so this should become less of a problem. As a workaround, you could just write a debug utility script that draws transparent primitive shapes in your running app/game.

**Comment by LeXXik** [comment] 2022-11-15 23:10
I suggest we close this, as there is now a PlayCanvas based collision shape view, as well as third party runtime viewers (e.g. https://playcanvas.com/project/744419/overview/ammo-debug-draw)

**Comment by willeastcott** [comment] 2022-11-16 00:35
Agreed.

**Closed by willeastcott** 2022-11-16 00:35 UTC
