### ISSUE TITLE
Screen Space Reflections

### ISSUE THREAD

**Issue by ImmanuelSamuel** [playcanvas/engine#1156] opened 2018-03-30 18:50 UTC
Would love to see this feature. Makes the demos more visually appealing.

**Comment by raytranuk** [comment] 2020-11-06 16:58
Related to: #2486

**Comment by mvaligursky** [comment] 2021-02-23 22:35
closing as duplicate of mentioned https://github.com/playcanvas/engine/issues/2486

**Closed by mvaligursky** 2021-02-23 22:35 UTC
Labels: area: graphics, feature request
