### ISSUE TITLE
Image element and material problem

### ISSUE THREAD

**Issue by Kangsi** [playcanvas/engine#1204] opened 2018-05-15 09:36 UTC
### Description

I'm unable to correctly show Image Elements in the game.

I'm trying to create UI elements in the game using materials. I have a sprite sheet and with a material I'm able to get the correct texture using offset and tiling. I assign that material to a Image Element, but it disappears in the editor and the game after reloading the browser.

* Tested on Chrome (66.0.3359.139) and Opera (52.0.2871.99)
* https://playcanvas.com/project/554848/overview/image-element-with-material

### Steps to Reproduce

1. Import the sprite sheet. 
2. Create a new material.
3. Change the settings of that new material.

![image](https://user-images.githubusercontent.com/8733899/40048197-e6cca5f6-5831-11e8-889f-d31d68b6a603.png)

4. Add a 2D Screen to the root and a Image element to the 2D screen.
5. Assign the new material to the Image element. (If you already have a launched game running, it will be visible in the game)

![image](https://user-images.githubusercontent.com/8733899/40049000-e1d22e48-5833-11e8-89e7-c622e70ba48a.png)

6. Reload either the editor or the launched game and the Image Element will be invisible.

![image](https://user-images.githubusercontent.com/8733899/40049038-f32d7d96-5833-11e8-88a4-1a74f0fbd611.png)

**Comment by taelg** [comment] 2018-09-12 20:13
i've spend all day trying to figure out what was i doing wrong :(

**Comment by etiennepinchon** [comment] 2021-06-13 11:18
Solved here: https://forum.playcanvas.com/t/solved-image-element-with-material-is-unvisible/14109/4

"Assign the World layer to the element as well, it will work"

![](https://forum-files-playcanvas-com.s3.dualstack.eu-west-1.amazonaws.com/original/2X/c/c8a0ad8ef558ac146783d29a6149120a2059e41e.jpeg)

**Comment by yaustar** [comment] 2021-06-14 13:10
The issue is by default, a model with material that has no opacity/transparency, will render on an opaque sub layer. The only available UI sub layer is the transparent one therefore you either have to use a different layer so you can add the opaque sub layer or change the material so it renders on the transparent sub layer as mentioned here: https://forum.playcanvas.com/t/solved-image-element-with-material-is-unvisible/14109/7?u=yaustar

**Comment by mvaligursky** [comment] 2024-06-27 11:21
Reading this, I don't think there's an engine issue here, so closing. Please re-open if needed.

**Closed by mvaligursky** 2024-06-27 11:21 UTC
Labels: area: ui
