### ISSUE TITLE
Resolution problem

### ISSUE THREAD

**Issue by kyousuke916** [playcanvas/engine#1185] opened 2018-04-27 02:30 UTC
Dear PlayCanvas,

I want to make sure of a situation when I use iPhone with the browser "Chrome".
It seems it's a bug for IOS.

Editor: https://playcanvas.com/editor/scene/603969
Launch: https://launch.playcanvas.com/603969?debug=true

iPhone6s plus + Chrome
Setting -> RENDERING -> Resolution=1920x1080 mode=Auto(importent)

Situation:
　
First, I set the screen to landscape mode and turn Chrome on to Launch location.
The upper left corner shows the width and height of the current graphicsDevice.
My iPhone6s plus shows 601/338.
(see image1)

Then turn the screen to Portrait mode. It becomes 414/233.
(see image2)

Then I turn the screen to landscape mode again  The graphicsDevice still shows 414/233? It's obvious that the picture becomes blurred.
(see image3)

I've tried other browsers. With Firefox it also happend like this way but Safari worked normally.
It also happened on Instant Game which was published to Facebook. Is it a bug?
By the way, It seems that this problem is only encountered on iOS, and not on android.

thanks

![image1](https://user-images.githubusercontent.com/7872445/39341419-b3be1d46-4a05-11e8-88eb-4f45d6202920.PNG)
![image2](https://user-images.githubusercontent.com/7872445/39341421-b3e73e1a-4a05-11e8-93c6-cfde1aded7ea.PNG)
![image3](https://user-images.githubusercontent.com/7872445/39341417-b3938f2c-4a05-11e8-8f27-3a7aebb20d92.PNG)

**Comment by willeastcott** [comment] 2021-05-14 11:33
Hey @yaustar, I'm surprised to see this is still a problem in iOS Chrome. Assigning you for now since you've been investigating resolution weirdness on iOS recently.

**Comment by yaustar** [comment] 2021-05-14 11:38
I've seen this issue in the launcher reflow where the initial width and height is different to subsequent resize/reflow calls.

I'm hoping to fix this with our plan that the launcher/HTML page handles the DOM sizing and the engine adapts.

**Comment by willeastcott** [comment] 2021-12-26 17:49
I just confirmed that this issue no longer happens in Chrome on iOS. I tested on an iPhone 6S using Chrome 92.0.4515.90, iOS 12.5.5. Closing. If you believe there are any further unresolved issues related to this, please follow up and we can reopen the issue.

**Closed by willeastcott** 2021-12-26 17:49 UTC
Labels: bug, area: graphics
