### ISSUE TITLE
Banding artifacts with envAtlas

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#4195] opened 2022-04-12 18:33 UTC
Problem with envAtlas, rgbm, maybe it's data loss in the alpha channel?
https://playcanvas.github.io/#/graphics/material-physical

Used video RTX 3060 for laptop:
![image](https://user-images.githubusercontent.com/22077882/163029699-4edd4391-a65e-426a-aa75-2c4c9e1042aa.png)

**Comment by willeastcott** [comment] 2022-04-12 20:37
It seems this is specific to your configuration. This is Win10 + Chrome + NVidia Quadro T2000:

![image](https://user-images.githubusercontent.com/697563/163049501-9fcea0f2-ae15-4a93-a42f-13d45ef4cff3.png)

**Comment by maungers** [comment] 2022-04-12 21:18
Probably need to check on other RTX 30xx laptop graphics cards. RTX 3090 for desktop - no artifacts.

**Comment by willeastcott** [comment] 2022-04-13 09:57
Any ideas what might be going on here, @slimbuck?

**Comment by maungers** [comment] 2022-04-13 15:54
Update.
It turned out that the integrated video card was used.
Enable discrete GPU turned out only in this way:
![image](https://user-images.githubusercontent.com/22077882/163220738-ca7256d7-f012-47d2-848b-3802d29cbdf9.png)

Thus, there are no artifacts on the RTX 30xx video card.
Artifacts are on the integrated video card: Intel Iris Xe Graphics

**Comment by maungers** [comment] 2022-04-13 16:20
Update2.
Another laptop.

ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2, OpenGL 4.5.0)
![image](https://user-images.githubusercontent.com/22077882/163225549-080eef3b-1543-4abb-9569-638b7d31e5b8.png)

**Comment by slimbuck** [comment] 2022-04-14 10:25
Hi @maungers,

Thanks so much for reporting this issue! I'll try repro on my side so I can investigate.

**Comment by slimbuck** [comment] 2022-04-14 11:13
Hmm unfortunately I can't repro on my side. I tried on my windows laptop running a GTX 1050 Ti without any luck. I also tried my macbook, swiftshader and linux. No problems on any of them.

**Comment by maungers** [comment] 2022-04-14 11:36
Yes, this is quite rare. I have 1070 - no artifacts.
I've only seen this on two laptops.

**Comment by Maksims** [comment] 2022-04-15 10:41
> Hmm unfortunately I can't repro on my side. I tried on my windows laptop running a GTX 1050 Ti without any luck. I also tried my macbook, swiftshader and linux. No problems on any of them.

Try using nvidia control panel, switching Chrome to integrated GPU, then restart computer, and try checking webglreport.com if it reports Integrated. Bear in mind, Chrome might still be running as a process, so it will not switch GPU, so restart or force close through task manager is required.
On macs, often integrated GPU is used by default.

Also, uninstalling nvidia drivers and disabling it, will force integrated GPU.
And make sure you open it using actual laptops screen, not external monitor, as it is almost always will run over dedicated GPU.

**Comment by willeastcott** [comment] 2022-10-21 12:35
@GSterbrant has reproduced the originally reported issue on the Intel Iris Xe integrated GPU. It is unrelated to PlayCanvas specifically. With DX11 (doesn't happen with the OpenGL ANGLE backend), the GPU is unable to filter the alpha channel correctly. Our intention is to report this to Intel directly.

**Comment by willeastcott** [comment] 2023-02-23 16:23
Closing because this is a driver issue - not a PlayCanvas bug.

**Closed by willeastcott** 2023-02-23 16:23 UTC
Labels: bug, area: graphics
