### ISSUE TITLE
The WebXR AR Basic example look like the cubes are drifting

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2441] opened 2020-09-23 16:08 UTC
https://playcanvas.github.io/#xr/ar-basic.html

Not sure if it's an artifact of them being above the ground. When I tried it, it looked like it wasn't quite grounded in the world.

**Comment by Maksims** [comment] 2020-09-23 18:05
Might sound weird, but make sure your camera is clean on mobile (just clean it with cloth from finger oils). And environment is well light with non-solid colors on everything (so it easier to track for AR).

It uses `localfloor` reference space, which relies on underlying AR system to estimate height above the floor. 0 on Y axis, should be the floor. If that underlying system is unable to estimate properly high above the floor, then different approach can be used, by using `local` reference space, and asking user to point to the floor and use Hit Test API or other methods to pick floor surface and that way you will find out relative Y difference (floor height).

If things drift around, this is due to underlying AR computer vision issues. AR is not perfect on every device, high end devices get better, but still, drifting is still a thing.

**Comment by mvaligursky** [comment] 2022-11-15 12:49
I checked the example code and it places the cubes on the ground, but I agree they're not placed on the ground in the world, but a bit above.

**Comment by willeastcott** [comment] 2024-12-15 16:27
I just tested this using the Immersive Web Emulator and the cubes are definitely placed correctly:

![image](https://github.com/user-attachments/assets/3cecce39-e117-450c-8a1b-a5ec425c2f33)

So the issue, as @Maksims said, is just down to the limitations of the underlying AR system. It's not a bug in the engine or example. Closing.

**Closed by willeastcott** 2024-12-15 16:27 UTC
Labels: bug, area: xr
