### ISSUE TITLE
Skybox rendering incorrectly on iOS

### ISSUE THREAD

**Issue by jbromberg** [playcanvas/engine#5075] opened 2023-02-17 23:10 UTC
Skyboxes are not rendering properly on iOS (tested on both Safari & Chrome). It renders perfectly on Chrome desktop.

Below are two screenshots of the issue and repro project.

![image](https://user-images.githubusercontent.com/58891459/219814303-0f06a41e-3862-43ca-9cca-2fd953b4bbde.png)
<img width="1507" alt="Screen Shot 2023-02-17 at 6 08 02 PM" src="https://user-images.githubusercontent.com/58891459/219814331-9a31fe30-e5c0-4a42-a554-a606bc1f6690.png">

Repro project: https://playcanvas.com/project/1028995/overview/skybox

**Comment by mvaligursky** [comment] 2023-02-22 16:35
I can confirm this on iPhone XR 16.1.1

**Comment by mvaligursky** [comment] 2023-02-23 08:27
I updated it to 16.3.1 and its still not working.

**Comment by mvaligursky** [comment] 2023-02-23 12:20
I was testing this by changing the shader .. and suddenly it worked. I reverted my change and it still works. I can no longer repro this on my exported build of this hosting locally.

But I can repro this on my MacBookPro. About 50% of times it loads correctly, the rest incorrectly. See screenshots and captures. For some reason that one face of the cube map is darker. 

<img width="1151" alt="Screenshot 2023-02-23 at 12 14 52" src="https://user-images.githubusercontent.com/59932779/220904013-f589b8da-ed23-4f67-b8d2-ca73652131b6.png">

<img width="1154" alt="Screenshot 2023-02-23 at 12 15 30" src="https://user-images.githubusercontent.com/59932779/220904027-38e38484-40c0-4849-b1e7-d2a2b86ac328.png">

<img width="1868" alt="Screenshot 2023-02-23 at 12 17 36" src="https://user-images.githubusercontent.com/59932779/220904057-aba457a4-4242-4b48-8964-722806845a4b.png">

<img width="1870" alt="Screenshot 2023-02-23 at 12 17 46" src="https://user-images.githubusercontent.com/59932779/220904092-72723da7-de4b-4b91-ab2b-505d06862904.png">

**Comment by slimbuck** [comment] 2023-02-23 12:21
So the image is randomly appearing upside-down?

**Comment by mvaligursky** [comment] 2023-02-23 12:21
I also tested jpg vs png and both were failing on iOS, so that does not make a difference. The test that is failing on Mac is using jpgs.

**Comment by slimbuck** [comment] 2023-02-23 12:22
Could you check if ImageBitmap is being used?

**Comment by mvaligursky** [comment] 2023-02-23 12:23
I don't think image changes up-down direction. See the image in on the right side of the Spector captures. Those are the same texture, but occasionally come out darker, like if occasional extra GAMMA is applied or something.

**Comment by slimbuck** [comment] 2023-02-23 12:25
The red TEXT in the first two screenshots are different way up though?

**Comment by slimbuck** [comment] 2023-02-23 12:25
oh but the camera has moved too, ignore me :)

**Comment by mvaligursky** [comment] 2023-02-23 12:27
supportsImageBitmap is null on my Mac

**Comment by mvaligursky** [comment] 2023-02-23 12:36
this is my repro on MacOS .. unzip, use local hosting .. and reload in Chrome, look up with the camera. Occasionally, the top cubemap face is correct, other times its darker color.

[test.zip](https://github.com/playcanvas/engine/files/10813519/test.zip)

**Comment by mvaligursky** [comment] 2023-02-23 12:42
Browsers on my macOS (did maybe 30 reloads each)

Safari - always incorrect (dark)
Firefox - always correct (light)
Chrome & Chrome Canary - randomly dark or light

**Comment by yaustar** [comment] 2023-02-23 12:50
I can't reproduce on Chrome 109.0.5414.119 (Official Build) (arm64) MacOS 12.6.3 (21G419)

But I can on Safari

**Comment by mvaligursky** [comment] 2023-02-23 12:52
When I force supportsImageBitmap to true, I always get correct behaviour on Chrome and FF, and always incorrect in Safari.

**Comment by yaustar** [comment] 2023-02-23 12:56
Looking at texture tools on Chrome, Safari and what MacOS preview gives me and it does look darker, even as standalone

<img width="2241" alt="image" src="https://user-images.githubusercontent.com/16639049/220912547-e5650ac1-b3c4-45f0-8aac-b52641b5092b.png">

**Comment by slimbuck** [comment] 2023-02-23 12:57
does the jpeg have a color profile?

**Comment by slimbuck** [comment] 2023-02-23 12:59
yep
<img width="523" alt="Screenshot 2023-02-23 at 12 59 25" src="https://user-images.githubusercontent.com/11276292/220913265-cdb3a10e-9579-4e77-adb4-a2d7f4dcead2.png">

**Comment by yaustar** [comment] 2023-02-23 13:02
Confirmed, converting that top image to SRGB fixes the issue 

https://playcanvas.com/project/1042614/overview/f-skybox

**Comment by mvaligursky** [comment] 2023-02-23 14:25
related https://github.com/playcanvas/engine/issues/2424

**Comment by jbromberg** [comment] 2023-02-23 18:13
Can confirm the color profile was the issue. Thanks all!

**Comment by willeastcott** [comment] 2023-02-23 18:48
Awesome. So @mvaligursky, are we good to simply close this?

**Comment by mvaligursky** [comment] 2023-02-23 20:40
I think it'd be good to see if we can detect this, and log a warning or simply ignore the profile.

**Comment by mvaligursky** [comment] 2023-02-24 09:21
Quick search does not find an easy way to see if the image has embedded color profile. We already have a ticket linked just above to investigate handling of the color profile, so I'll close this one.

**Closed by mvaligursky** 2023-02-24 09:21 UTC
Labels: bug, area: graphics
