### ISSUE TITLE
[events.js:60]: Uncaught ReferenceError: log is not defined

### ISSUE THREAD

**Issue by h0lmiew** [playcanvas/engine#2854] opened 2021-02-11 10:00 UTC
### Description

In one of our test projects we get the following error immediately upon trying to open play mode. We are not seeing it in other projects, so not sure what causes it in the first place.

[events.js:60]: Uncaught ReferenceError: log is not defined

```
    ReferenceError: log is not defined
    at Editor.Events.emit (https://launch.playcanvas.com/editor/scene/js/events.js:60:13)
    at Connection. (https://launch.playcanvas.com/editor/scene/js/launch.js:11859:20)
    at emitOne (https://launch.playcanvas.com/editor/scene/js/launch.js:181:13)
    at Connection.emit (https://launch.playcanvas.com/editor/scene/js/launch.js:259:7)
    at https://launch.playcanvas.com/editor/scene/js/launch.js:2621:20
    at Item.run (https://launch.playcanvas.com/editor/scene/js/launch.js:2467:14)
    at drainQueue (https://launch.playcanvas.com/editor/scene/js/launch.js:2437:42)
```

Upon opening the events.js (that I do believe is native playcanvas), I can see the line 60
**log.error(ex);**

should probably instead be
**console.error(ex);**

### Steps to Reproduce

1. Open playmode
2. Immediately before loading bar starts moving, error is thrown

**Comment by mvaligursky** [comment] 2021-02-11 10:36
duplicate of https://github.com/playcanvas/editor/issues/233

we're aware of the issue and will have a fix shortly. Is this blocking you? 
@yak32 - any possible workaround?

**Comment by yaustar** [comment] 2021-02-11 11:20
There's an issue in our launcher code that catches errors in the application :( 

Looking into a fix for this soon.

**Comment by h0lmiew** [comment] 2021-02-11 11:36
> duplicate of [playcanvas/editor#233](https://github.com/playcanvas/editor/issues/233)
> 
> we're aware of the issue and will have a fix shortly. Is this blocking you?

No, we found a different way to test what we were working on, just wanted to mention it.

**Comment by yak32** [comment] 2021-02-16 21:34
the issue is already fixed, https://launch.playcanvas.com/editor/scene/js/events.js doesn't contain log anymore.

**Comment by yaustar** [comment] 2021-02-16 21:59
We may have more of these in the codebase @yak32 :(

https://forum.playcanvas.com/t/referenceerror-log-is-not-defined/17905/4

**Comment by yak32** [comment] 2021-02-17 10:16
yes, I see, going to fix it today

**Comment by yak32** [comment] 2021-02-17 13:09
the fix is merged, we will deploy it soon

**Comment by yak32** [comment] 2021-02-19 14:37
the fix is deployed, the issues should be fixed now.

**Closed by yak32** 2021-02-19 14:37 UTC
Labels: bug
