### ISSUE TITLE
Performance drop in v1.61 when using clustered lights

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#5086] opened 2023-02-21 19:51 UTC
It seems there is a potentially big performance hit when using clustered lights (omni/spot) in v1.61. The performance hit seems to be coming for the Standard Material shader, specifically the pixels lit by a light seem to be running slower.

Repro project: https://playcanvas.com/editor/scene/1668679

v1.60
![image](https://user-images.githubusercontent.com/29543178/220444295-88139de0-26b9-444e-8a39-7f44b12d6d9e.jpg)

v1.61.1
![image (1)](https://user-images.githubusercontent.com/29543178/220444336-807156ad-23ca-4e78-b4b2-56df3f520bcb.jpg)

The performance hit may not seem that big (~2ms higher), but if you have multiple materials in a scene affected by a clustered light then it becomes massive indeed when the camera moves closer to those pixels.

**Comment by querielo** [comment] 2023-02-21 21:31
I think the source of the problem is this commit: https://github.com/playcanvas/engine/commit/2a3948867fd5f6433c39c012fcb7379297e6e5c7#diff-aa6223ca3920bbf892c6771e25c5b499aed81e879448eccb5182c281320f296aL595

Because, it causes 4 times more texture lookups + it may be less cache-friendly.

**Comment by willeastcott** [comment] 2023-02-21 21:45
Yeah, I suspect you're right there. If that's the case, we should back that change out and do another patch tomorrow.

**Comment by mvaligursky** [comment] 2023-02-22 10:35
Fixed in https://github.com/playcanvas/engine/pull/5088

**Closed by mvaligursky** 2023-02-22 10:35 UTC
Labels: bug, area: graphics, release: next patch
