### ISSUE TITLE
Looping animations from outside of game causing render loop issues

### ISSUE THREAD

**Issue by maxbbb** [playcanvas/engine#2403] opened 2020-09-02 19:00 UTC
### Description
This bug is written out in the context of iOS, but it might apply elsewhere. 

All of my company's games (Gamebytes) are made in Playcanvas, and we noticed an issue where when any playcanvas game is open, if there is a looping animation coming from any system process, whether it be inside or outside of the app that is hosting the Webview, the render loop starts to flicker between taking ~16ms and ~32ms every frame. Initially I believed this to be an iOS WKWebview bug, but when reproducing this with a Babylon.js game you do not see the same issue. 

While this might sound very specific, this is a larger issue because it's also reproducible in every Snap game on iOS. Because they don't have FPS monitors some are harder to tell than others, but if you go to Super Snappy Bowling and turn the quality setting to high and then either press the voice call button which initiates an animation or have someone be typing in the normal Snapchat messaging which shows an animated typing indicator, you will see the pin animation around the ball become choppy until the animation stops. I have not tried but I would bet this is also reproducible in some context in Facebook instant games. 

Additionally if you go to our app Gamebytes in the iOS app store and play a game in iMessage, if someone is typing while you play (due to the animation of the typing indicator) you will notice this issue. 

### Steps to Reproduce

[Here](https://youtu.be/XLacKlC56tk) is link to a video the bug being produced in Facebook messenger, it is specifically NOT a regular screen recording because for whatever reason the bug is not reproducible while screen recording. I imagine this has something to do with how iOS handles rendering differently when screen recording. In the video the maps button is pressed in order to initiate the looping pulse animation on your location. We have seen sometimes very randomly this issue will not happen, but it does happen around 80% of the time so if it doesn't reproduce just try again it will likely happen.

1. Open a playcanvas game with an FPS monitor (or some animating objects so that you will notice the slowdown) inside an app that might contain some looping animations in the same context
2. Try to open the game without the looping animation, see that it is fine, and open the game with the looping animation playing and see that it is now slowed down.

**Comment by willeastcott** [comment] 2020-09-02 21:48
Thanks for the detailed bug report @maxbbb! We will investigate straight away and get back to you.

Can you give me the link to a simple Babylon app that doesn't exhibit the issue? Then we'll be able to compare and contrast the code. It could be related to how we utilize requestAnimationFrame perhaps.

**Comment by maxbbb** [comment] 2020-09-02 23:07
Thank you! Any of the playground projects would work, I picked a more intensive one for mobile just to be sure it would be more visually obvious if the issue appeared but they all have FPS counters. This one would work fine - https://playground.babylonjs.com/#5W5B6W#3

**Comment by mvaligursky** [comment] 2020-09-03 12:17
Hi @maxbbb 

Thanks for the report, it sounds important to solve the problem. We've tried to repro the issue on 3 devices so far without success. The devices and installed os:
iPhone XR, 14.0
iPhone 7, 13.3.1
iPhone 8 Plus, 13.7

First we tried Facebook messenger, running these playcanvas apps
https://playcanv.as/p/VRCXOsxi/          (the one you used in the video)
https://launch.playcanvas.com/978451?debug=true&ministats=true
http://playcanvas.github.io/#graphics/mesh-generation.html

with the last link, I tried different examples there as well, some CPU and some GPU limited.
All runs 60fps apart from some that cannot and those run 30fps, but we cannot see frame time jumping around. Animations seems all smooth.

We played Super Snappy Bowling, quality on both high and low, typing, animating the speak button, but the game runs at 60fps and the pin rotates very smoothly the whole time. In low settings it runs at 30fps, but no stuttering.

We also tried enabling some experimental features (webgl2) in Safari, also tried Low Power mode (which drops all apps to 30fps, but no visible stuttering, running well at 30).

 We tried running your games in iMessage as well, but could not figure out how to do it (none of us use iMessage, and it was failing to send sms with the link?). In my phone I don't have sim card, and that is likely related as the app is probably not set up yet.

Would you have some additional suggestions of what / how to test to reproduce it?
What devices and iOS versions can you repro it on?
Any experimental features enabled in Safari?
Any other apps running that could be interfering?

Thanks
Martin

**Comment by leonidaspir** [comment] 2020-09-03 16:18
I was able to reproduce the issue on an iPhone 10 running iOS 13.6.1, following the steps @maxbbb recorded on his video.

2 out of 3 times opening an empty Playcanvas scene with the FPS running, the FPS drops to 40FPS. I wasn't able to notice the same on the Babylon.js scene.

https://www.dropbox.com/s/0kv1twwp7m1507i/20200903_164434.mp4?dl=0

**Comment by maxbbb** [comment] 2020-09-03 16:33
Thanks @leonidaspir. 

First of all thank you @mvaligursky for being so quick to take a deep look into this. I'm sorry that you're having trouble reproducing the issue. 

I checked on an iOS 14 device and am able to confirm that I could not reproduce the issue there, which is good. 

The two other devices I've tested this issue on are on iOS 13.4 and iOS 13.6.1. On both of those I was able to reproduce the issue consistently, and I do not have any experimental features enabled on either device. I do not have easy access to iOS 13.7 or iOS 13.3.1 so I cannot confirm if possibly the issue just does not exist on those versions. 

As far as other apps interfering, I closed out of all apps and restarted to try again and was stilling seeing the issue. If possible, I would try on one of these OS versions: 13.6, 13.6.1, or 13.4 and see if you are still not able to reproduce the issue. 

For our iMessage app yes you need iMessage in order for the games to send and be played as they use the iMessage extension framework to function, but it's much easier to reproduce this issue in Facebook messenger anyway.

**Comment by willeastcott** [comment] 2020-09-04 17:31
We are wondering whether the use of `cancelAnimationFrame` may have something to do with this:

https://github.com/playcanvas/engine/blob/master/src/framework/application.js#L2388

cc @Maksims

**Comment by Maksims** [comment] 2020-09-04 21:08
> We are wondering whether the use of `cancelAnimationFrame` may have something to do with this:
> 
> https://github.com/playcanvas/engine/blob/master/src/framework/application.js#L2388

Based on Specification, cancelAnimationFrame during executed animation frame callback should not do any difference, as callback is already removed from the callbacks list: https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animationframeprovider-cancelanimationframe

It worth testing it out, as it might be that iOS decided not to follow Specs precisely, and have some extra underlying logic, that can mess with executed animation frame callbacks that have `cancel` called against during execution. But I would assume it would not render at all then.

**Comment by maxbbb** [comment] 2020-09-09 18:50
So I just tested commenting out the `cancelAnimationFrame` and building the fps project with the modified version of the engine and I"m still seeing the same thing. The link is [here](http://www.basketball2.gamebytes.io.s3-website-us-east-1.amazonaws.com/) if you want to check it out, but I'm not sure if you're still having trouble reproducing this.

**Comment by slimbuck** [comment] 2020-09-11 16:27
I managed to repro this in messenger using an empty project with ministats (https://launch.playcanvas.com/879199?ministats=true) :

<img width="375" alt="Screenshot 2020-09-11 at 17 13 20 2" src="https://user-images.githubusercontent.com/11276292/92949761-88095f80-f453-11ea-9db3-b709e0fecd2a.png">

In the frame timing history you can see before and after the slowdown. Frame graph shows the time reported to playcanvas by the browser when requestAnimationFrame is invoked.

I found I can sometimes trigger the slowdown state by double tapping the home button and then returning to the app.

**Comment by mvaligursky** [comment] 2020-09-17 11:00
@maxbbb - we're just curious if you've updated any devices showing the issue to iOS14 to see if that might change the situation, considering both of us could not repro it on iOS14 beta devices?

**Comment by Maksims** [comment] 2020-09-17 12:49
I believe this can be the mechanics that browsers implement behind timings of requestAnimationFrame, which is left to vendors to implement, so it can vary between browsers and possibly platforms: requestAnimationFrame can be forcibly throttled by the browser, if browser decides that it cannot fit into 16ms frame or some other reasons (low power mode, cross-origin iframes, etc). To avoid floating FPS between 30 and 60, it switches to 30 by force. Floating FPS is worse for user experience than fixed.

Here is actual changelogs in WebKit that describes throttling:
https://trac.webkit.org/changeset/215070/webkit
https://bugs.webkit.org/show_bug.cgi?id=168837

There are some links related to this from google:
https://popmotion.io/blog/20180104-when-ios-throttles-requestanimationframe/
https://mattperry.is/writing-code/browsers-may-throttle-requestanimationframe-to-30fps

**Comment by maxbbb** [comment] 2020-09-22 17:18
I am not able to reproduce in the final version of iOS 14, so that's good. 

@Maksims that makes sense that it should do that, but from my own testing it is floating between 30 and 60 and I haven't used the mini-stats but I believe that's what the image above is showing as well.

**Comment by mvaligursky** [comment] 2020-12-04 17:50
I've close this now as it seems to be gone with iOS14.

**Closed by mvaligursky** 2020-12-04 17:50 UTC
Labels: area: graphics, bug
