### ISSUE TITLE
Oculus Browser - Error loading audio url: <mp3-file-name>: Unable to decode audio data

### ISSUE THREAD

**Issue by ChiefBreakeverything** [playcanvas/engine#3511] opened 2021-09-22 14:04 UTC
### Description

* Happens on Oculus Browser 17.0.0.6.22.318015459 (Chromium 93.0.4577.62) for Quest 2
* Doesn't happen on Windows 64-bit Chrome 93.0.4577.82
* Doesn't happen on Firefox Reality (12.2) for Quest 2
* Different hosting doesn't seem to make a difference (happens when self-hosted or internally hosted i.e. https://launch.playcanvas.com/xxxxxxx)
* It only happens about 50% of the time (?)
* The mp3 files can be inspected and played back fine from the Editor preview panel
* The mp3 files I've tested are between 3-5mb and durations between 2-3 minutes.
* I've tested many different mp3 files to ensure there are no file-specific issues.
* I haven't tested other audio encodings or formats.
* The issue is highly, highly reproducible and is affecting our team (10+ users) on a daily basis.
* I'm happy to provide more information if need be.

### Steps to Reproduce

1. Import any (?) mp3 file in a PlayCanvas project and set its preload flag to true.
2. Alternatively, you can connect Chrome DevTools through ADB ([guide](https://raygun.com/blog/debug-android-chrome/)) and call `pc.app.assets.load(anyMP3Asset)` through the console. This is preferred since you can also use `anyMP3Asset.unload()` to easily try again and inspect the error in detail.
3. Launch the PlayCanvas application
4. There is a very high likelihood of encountering the `Unable to decode audio data` error. If it doesn't happen, simply refresh or unload/reload. It seems to be more likely to happen than less.
5. The resulting error is internal to PlayCanvas and therefore ceases further execution of the app.

### Error lines

If I follow the debug links found attached to the error in Chrome DevTools, it seems to originate from this line in the AudioHandler function (also pictured in the screenshots)

```
	var AudioHandler = function () {
		function AudioHandler(manager) {
			this.manager = manager;
			this.maxRetries = 0;
		}

		var _proto = AudioHandler.prototype;

		_proto._isSupported = function _isSupported(url) {
			var ext = path.getExtension(url);

			if (toMIME[ext]) {
				return true;
			}

			return false;
		};

		_proto.load = function load(url, callback) {
			if (typeof url === 'string') {
				url = {
					load: url,
					original: url
				};
			}

			var success = function success(resource) {
				callback(null, new Sound(resource));
			};

			var error = function error(err) {
				var msg = 'Error loading audio url: ' + url.original;

				if (err) {
					msg += ': ' + (err.message || err);
				}

				console.warn(msg);
				callback(msg); // < ----- This guy right here!
			};

			if (this._createSound) {
				if (!this._isSupported(url.original)) {
					error("Audio format for " + url.original + " not supported");
					return;
				}

				this._createSound(url.load, success, error);
			} else {
				error(null);
			}
		};
```

![image](https://user-images.githubusercontent.com/4685982/134352407-b344d6b6-3f50-4aba-827a-edc2617f9217.png)
![image](https://user-images.githubusercontent.com/4685982/134352534-14484474-0ef4-4303-bd26-9a01efff9835.png)

**Comment by yaustar** [comment] 2021-09-22 16:54
I'm unable to reproduce in this test project: https://playcanvas.com/project/833523/overview/oculus-vr-mp3-bug

Can you provide a test project that shows this issue please?

**Comment by ChiefBreakeverything** [comment] 2021-09-23 08:07
Hm, this project doesn't seem to cause the error for me either.

I'll create an example project with the error and link it here shortly.

**Comment by yaustar** [comment] 2021-09-23 09:41
If the MP3 is licensed, make it private and give 'yaustar' read access please.

**Comment by ChiefBreakeverything** [comment] 2021-09-23 11:59
Done! I added a small setup for quickly loading and unloading some assets.

It's definitely happening (eventually) with this set of mp3s but is happening much more frequently in our main project (because there are even more assets I suppose).

Let me know if it's still not reproducible somehow.

**Comment by yaustar** [comment] 2021-09-23 14:49
I've only managed to reproduce it once on the test project out of refreshing ~20 times. Trying again with a fork but just stuffing more files in it

**Comment by yaustar** [comment] 2021-09-23 15:16
I've been trying for the last 30mins and been only able to reproduce it that one time :(

**Comment by oyapiro** [comment] 2021-09-24 12:35
I think it is the same issue related to this.

### Description

- It happens on Safari 15(15612.1.29.41.4, 15612) on macOS Catalina 10.15.7（19H1417）. Not happens on Safari 12 and Mojave, or Safari 15 and Big Sur.
- It happens always.
- Dev Console says "Error loading audio url: foobar.m4a" and "Unhandled Promise Rejection: EncodingError: Decoding failed".

### Steps to Reproduce

- Fork "Flappy Bird" project from https://playcanvas.com/explore/featured and launch it on Safari 15 on Catalina.

**Comment by yaustar** [comment] 2021-09-24 12:36
> I think it is the same issue related to this.
> 
> ### Description
> * It happens on Safari 15(15612.1.29.41.4, 15612) on macOS Catalina 10.15.7（19H1417）. Not happens on Safari 12 and Mojave, or Safari 15 and Big Sur.
> * It happens always.
> * Dev Console says "Error loading audio url: foobar.m4a" and "Unhandled Promise Rejection: EncodingError: Decoding failed".
> 
> ### Steps to Reproduce
> * Fork "Flappy Bird" project from https://playcanvas.com/explore/featured and launch it on Safari 15 on Catalina.

I can't reproduce this on Safari 15. The audio files in that project are also mp3s, not m4as

**Comment by oyapiro** [comment] 2021-09-24 12:49
### Error lines

[Error] Error loading audio url: sfx_die.mp3
　　（anonymous関数） (launch.js:15181)
　　 _onFailure (playcanvas-stable.dbg.js:36752)
　　（anonymous関数） (playcanvas-stable.dbg.js:36689)
　　error (playcanvas-stable.dbg.js:33183
<img width="794" alt="スクリーンショット 2021-09-24 21 45 07" src="https://user-images.githubusercontent.com/1418022/134676814-98135974-0c3a-47a3-934c-02dc9456ad03.png">
)

**Comment by ChiefBreakeverything** [comment] 2021-09-25 07:22
> I've been trying for the last 30mins and been only able to reproduce it that one time :(

Ah, hm... I'll see if I can increase its reproducibility (so its more like what we're seeing in our main project) and I'll message you when it's easier to see.

**Comment by ChiefBreakeverything** [comment] 2021-09-27 06:34
@yaustar I've recreated the conditions much better now in a different project, I've added you like before. It's happening the exact same as in our project. We even get the Oculus Crash Corgi 😋

**Comment by yaustar** [comment] 2021-09-28 13:48
Confirmed reproducible. Not sure what is causing the issue at the moment tbh. I'm wondering if there is a limit somewhere on the browser?

**Comment by yaustar** [comment] 2021-09-28 14:02
@ChiefBreakeverything 

Unfortunately, it's starting to look like a browser/device specific issue for the Quest and similar devices.

At a guess, because the Quest has only 4GB of RAM, it's just runs out of memory and crashes the browser. I've tried it on a similar 4G Android device with a few more MP3s and it does the same thing, crashes the browser.

You will have to work around this issue by loading and using assets that you need at a time.

**Comment by yaustar** [comment] 2021-09-28 14:04
@oyapiro I've moved your issue to a new issue as it's unrelated from the looks of things. https://github.com/playcanvas/engine/issues/3525

**Comment by yaustar** [comment] 2021-09-28 14:10
Tried it on an Android device with 12GB of RAM and that load the scene fine so its looking more to be memory constraint.

**Comment by ChiefBreakeverything** [comment] 2021-09-29 04:39
I suspected as much. It's strange since the Mozilla Realities browser on Quest 2 has no problem, it might just be Oculus Browser specific.

We already are loading and unloading as needed, unfortunately 😦 specifically fetching all assets with tags, loading when needed and unloading when needed. eachAsset.loaded returns false afterwards, etc.

**Comment by yaustar** [comment] 2021-09-29 08:06
Hmm, I wonder if it be worth trying to load and unload a bunch of MP3s will cause the same issue? If it does, maybe there's s bug with unloading audio assets either in the engine or browser?

**Comment by ChiefBreakeverything** [comment] 2021-09-29 08:17
Yeah that's exactly what I tested out in that first shared project. I wasn't using the _exact_ same files so it wasn't identical, but it still happened even with as few as 8-ish mp3s totalling 44mb of memory. 44mb of audio with no other assets or code isn't gonna max out a Quest 2 😦

**Comment by yaustar** [comment] 2021-09-29 08:27
44MB of memory or 44MB total file size?

**Comment by ChiefBreakeverything** [comment] 2021-09-29 08:28
Ah file size, I wasn't able to check what it was taking up in memory sorry!

**Comment by willeastcott** [comment] 2024-12-15 15:47
We already have an issue for [streaming audio](https://github.com/playcanvas/engine/issues/601) so I'm closing this.

**Closed by willeastcott** 2024-12-15 15:47 UTC
Labels: bug, area: audio
