### ISSUE TITLE
No collision if linear factor of all axes is 0

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/engine#4884] opened 2022-11-24 11:21 UTC
I was trying to help a user creating a doorway with a door. I changed the original setup a bit. Unfortunately I can't get the door fully working, because there is no collision with the static wall. Steven found out that this is because the linear factor of all axes is set to 0, which is necessary because the door only rotates and does not move.

Forum topic:
https://forum.playcanvas.com/t/how-to-stop-door-from-rotating-too-much

Sample project:
https://playcanvas.com/project/1011862/overview/doorway

**Comment by yaustar** [comment] 2022-11-24 11:24
This is likely to be an Ammo issue and there would be very little we can do about it on the PlayCanvas side

**Comment by albertvanveen** [comment] 2022-11-24 11:26
Maybe someone can check this anyway. The recommendation is to complex for this simple use case.

**Comment by LeXXik** [comment] 2023-01-08 12:40
Yeah, that won't work. The short story is that Ammo collision solver needs a linear velocity to solve the collision. Since both bodies have not linear velocity - the wall (being static) and the door (it is zeroed out by linear factor set to zero), then the solver can't solve the collision. The player can still push the door, since one of the bodies have linear velocity (the player's capsule). As Steven suggested, one should use a hinge joint for a dynamic door. Or, you know don't physicalize it. Fake it with a static collider box in its place enabling/disabling (preventing player to go through if door is closed) and the door is just a visual mesh rotating, like in most games. Rotate the door to open and disable the static block, so player can go through. Close the door back and enable the static box.

**Comment by yaustar** [comment] 2023-01-09 09:46
Sounds like it's expected behaviour or a bug in Ammo/Bullet where setting linear to 0,0,0 means that it will only collide with other collision that has velocity (ie other dynamic objects). It's as though it's acting like a kinematic in this state.

I will close this ticket for now as we can't fix on the Engine side

**Closed by yaustar** 2023-01-09 09:46 UTC
Labels: bug, area: physics
