### ISSUE TITLE
Transparency issues on model with WebGL 1

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3213] opened 2021-06-04 11:09 UTC
Project: https://playcanvas.com/editor/scene/1170592

WebGL 1: https://launch.playcanvas.com/1170592?webgl1=true&debug=true
![image](https://user-images.githubusercontent.com/16639049/120792585-a8230680-c52d-11eb-99f5-322a6644f2bc.png)

WebGL 2: https://launch.playcanvas.com/1170592?debug=true
![image](https://user-images.githubusercontent.com/16639049/120792621-b53ff580-c52d-11eb-94f5-2c74fe7fca3e.png)

**Comment by mvaligursky** [comment] 2021-06-10 17:21
I'm not sure what the problem is exactly, but the material _lambert4_ has Alpha to Coverage ticked. This is not supported on WebGl1. When I untick the option, even webgl2 looks the same as webgl1. Is the project set up to take advantage of Alpha to Coverage? If it is, this cannot be used on WebGl1.

**Comment by willeastcott** [comment] 2024-04-28 20:41
Closing because the difference was caused by alpha to coverage being enabled and we're stripping WebGL 1 support from the engine anyway.

**Closed by willeastcott** 2024-04-28 20:41 UTC
Labels: bug, area: graphics
