### ISSUE TITLE
Cloned entity is rendered without being added to root graph node

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2247] opened 2020-07-06 17:13 UTC
Setup: 
1, Create an entity and disable it.
2. Create a clone of it and enable the clone.
3. Do not add the clone to the graph (e.g. `this.app.root.addChild(clone);`);

In this case, the clone is still rendered and visible in the scene. However, because it was not added to any graph nodes explicitly, some API calls will fail. For example, `this.app.root.findComponents();`, or any other methods that rely on traversing the root to locate the entity.

**Comment by yaustar** [comment] 2020-07-06 19:52
Duplicate of https://github.com/playcanvas/engine/issues/2183

**Closed by yaustar** 2020-07-06 19:52 UTC
