### ISSUE TITLE
Primitives with procedural material don't clone properly

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#425] opened 2015-10-31 11:47 UTC
To repro:
Create an entity with basic primitive (e.g. box)
Create a pc.PhongMaterial and set it on this.entity.model.material.
Clone the entity.

Result:
The material is not cloned.

See the physics engine example to see this bug.

**Comment by daredevildave** [comment] 2015-11-03 16:29
Why is this expected behaviour? The material is an asset. We don't clone assets when we clone entities.

**Comment by Maksims** [comment] 2015-11-03 16:34
Material is a resource of an asset. And I believe we actually do clone materials for each model instance individually.

**Comment by vkalpias** [comment] 2015-11-03 17:41
The problem is not that the material itself is not cloned but rather the model does not have the material of the original model.

**Comment by vkalpias** [comment] 2015-11-18 09:56
Fixed in https://github.com/playcanvas/engine/commit/7ce6c5e7fc610c9a797af10efcc36413a4fd0507

**Closed by vkalpias** 2015-11-18 09:56 UTC
Labels: bug
