### ISSUE TITLE
Cubemap textures upside down when DXT compression is active

### ISSUE THREAD

**Issue by anox1337** [playcanvas/engine#2564] opened 2020-11-17 19:29 UTC
Hello team!

We encountered an issue where setting DXT compression to 'active' on textures used by a cubemap will mirror the textures when running the scene.

Example project:
https://playcanvas.com/project/738454/overview/cubemap-compression-bug

Removing the compression will return the cubemap textures to their correct orientation.

Would be great if someone could look into this issue.

Thanks!

**Comment by slimbuck** [comment] 2020-11-18 10:13
Hi @anox1337,

Thanks for reporting, this is actually a known issue. The problem is that playcanvas treats images upside-down. We plan to address this, but it's not a small job.

For now it's unfortunately not possible to use the editor-generated compressed textures as cubemaps.

Closing this ticket as dup of #1983.

Thanks!

**Closed by slimbuck** 2020-11-18 10:13 UTC
