### ISSUE TITLE
Rethink Material update mechanic

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#909] opened 2017-04-11 18:38 UTC
material.update() has two issues:
- unintuitive (people don't realize they have to call it)
- slow to perform (it updates things it doesn't need to etc)

We should redesign the material class to be better...

**Comment by willeastcott** [comment] 2017-12-11 02:19
Duplicate of #699. Closing.

**Closed by willeastcott** 2017-12-11 02:19 UTC
Labels: enhancement
