### ISSUE TITLE
Add UI help functions that allow for transformations between difference spaces and elements

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3075] opened 2021-04-09 14:41 UTC
The classic functions such as:
* UiScreenToWorld
* WorldToUiScreen
* ScreenToUiScreen
* UiScreenToScreen

And these would take into account the anchors, screen scale/blend etc.

Additionally, there is the scenario where a developer would like to move an element from one group to another while retaining it's UI screen position. 

Something like Unity's `void SetParent(Transform parent, bool worldPositionStays);` where the developer can set the flag to keep the current position of the entity/element when changing parents is pretty useful.

**Comment by Maksims** [comment] 2021-04-09 15:20
Duplicate of: https://github.com/playcanvas/engine/issues/1700

**Closed** 2021-04-09 15:23 UTC
Labels: area: ui, feature request
