### ISSUE TITLE
Cubemaps don't reload correctly

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#2271] opened 2020-07-11 12:45 UTC
Cubemap assets don't load correctly after calling `unload()` on them.

**Comment by willeastcott** [comment] 2021-03-22 20:31
Have you got a repro of the problem, @iXperiential? What are you observing exactly?

**Comment by iXperiential** [comment] 2021-03-22 20:49
I have multiple scenes, each one with its own cubemap used for the skybox and some materials.
In the editor, each cubemap is marked as not preloading and has a tag. 
I load them on the fly and unload them when jumping to a new scene.

The first time I jump into a scene it works. I see my cubemap being loaded and applied.
Then I jump back to the "hub" scene. I see my cubemap being unloaded.
If I try to go back to the first scene, PlayCanvas crashes during the loading process.

Uncaught TypeError: Cannot read property '_levels' of undefined
    at CubemapHandler.update (playcanvas-stable.js:32117)
    at onReady (playcanvas-stable.js:32203)
    at CubemapHandler.loadAssets (playcanvas-stable.js:32251)
    at CubemapHandler.load (playcanvas-stable.js:32008)
    at ResourceLoader._loadNull (playcanvas-stable.js:34752)
    at ResourceLoader.load (playcanvas-stable.js:34675)
    at AssetRegistry.load (playcanvas-stable.js:37236)
    at scriptType.PlayerControls.loadScene (PlayerControls.js?id=43075962&branchId=1b3a6284-4024-4423-a565-fb123dd70e58:622)
    at Application.<anonymous> (PlayerControls.js?id=43075962&branchId=1b3a6284-4024-4423-a565-fb123dd70e58:81)
    at Application.fire (playcanvas-stable.js:740)
launch.js:8069 TypeError: Cannot set property 'glossMap' of undefined
    at MaterialHandler._assignTexture (playcanvas-stable.js:33502)
    at MaterialHandler._onTextureLoad (playcanvas-stable.js:33516)
    at AssetReference._onLoad (playcanvas-stable.js:33105)
    at AssetRegistry.fire (playcanvas-stable.js:740)
    at _opened (playcanvas-stable.js:37203)
    at Array._loaded (playcanvas-stable.js:37227)
    at ResourceLoader._onSuccess (playcanvas-stable.js:34759)
    at Array.<anonymous> (playcanvas-stable.js:34709)
    at Worker.handleWorkerResponse (playcanvas-stable.js:36144)
console.error @ launch.js:8069
launch.js:8069 TypeError: Cannot set property 'diffuseMap' of undefined
    at MaterialHandler._assignTexture (playcanvas-stable.js:33502)
    at MaterialHandler._onTextureLoad (playcanvas-stable.js:33516)
    at AssetReference._onLoad (playcanvas-stable.js:33105)
    at AssetRegistry.fire (playcanvas-stable.js:740)
    at _opened (playcanvas-stable.js:37203)
    at Array._loaded (playcanvas-stable.js:37227)
    at ResourceLoader._onSuccess (playcanvas-stable.js:34759)
    at Array.<anonymous> (playcanvas-stable.js:34709)
    at Worker.handleWorkerResponse (playcanvas-stable.js:36144)
console.error @ launch.js:8069
launch.js:8069 TypeError: Cannot set property 'normalMap' of undefined
    at MaterialHandler._assignTexture (playcanvas-stable.js:33502)
    at MaterialHandler._onTextureLoad (playcanvas-stable.js:33516)
    at AssetReference._onLoad (playcanvas-stable.js:33105)
    at AssetRegistry.fire (playcanvas-stable.js:740)
    at _opened (playcanvas-stable.js:37203)
    at Array._loaded (playcanvas-stable.js:37227)
    at ResourceLoader._onSuccess (playcanvas-stable.js:34759)
    at Array.<anonymous> (playcanvas-stable.js:34709)
    at Worker.handleWorkerResponse (playcanvas-stable.js:36144)

If I mark the cubemap and its textures as "preload", the issue disappears.
Let me see if I can make a quick project to demo it.

**Comment by iXperiential** [comment] 2021-03-22 21:34
https://playcanvas.com/editor/scene/1116495

Press play. Press S to switch to the secondary cubemap and M to go back to the main one.

**Comment by slimbuck** [comment] 2021-03-22 21:46
Thanks so much for the repro. We'll get this sorted asap.

**Comment by slimbuck** [comment] 2021-03-23 10:21
The error in your repro doesn't match the error above?

**Comment by raytranuk** [comment] 2021-03-23 11:01
@iXperiential - I took a look and after a bit of debugging it looks like its just a typo in the project script: https://playcanvas.com/editor/code/777818?tabs=44702546 

changing:
```            this.currentLoaded = name;``` 
to: 
```            self.currentLoaded = name;``` 

fixes the issue.

**Closed by raytranuk** 2021-03-23 11:01 UTC
Labels: area: graphics, bug

**Comment by iXperiential** [comment] 2021-03-23 16:52
Thanks for fixing my test repro. I'll work on trying to make a reproducible case.
