### ISSUE TITLE
loadFromUrl sometimes stalls if loading assets that depend on same material

### ISSUE THREAD

**Issue by sdfgeoff** [playcanvas/engine#942] opened 2017-06-05 19:57 UTC
If I have asset1, and it uses material1 and material2
And I have asset2 and it uses material1 and material3

Then, in certain conditions* loadFromUrl will stall on loading the second asset. Some digging through the engine reveals that onLoadAsset (~line 498 of asset-registry.js) is not being called a sufficient number of times although self.loadFromUrl (~line 510 of asset-registery.js) is being called for each material required. I suspect some cache somewhere is soaking up the request and the callback isn't being run if it's in the cache.

I managed to solve the problem in my project by removing the shared material dependency, but this is not a correct solution. 

*Note on the "sometimes" nature of the issue:
If you call app.assets.loadFromUrl while iterating through a list (aka a typical usage), then this problem does not occur. Only once an asset (that uses a shared material) has finished loading before scheduling another loadFromUrl does this happen.

I'll try to make an example for this, but have been chasing this issue all afternoon and need to take a break.

**Comment by willeastcott** [comment] 2019-12-26 01:22
Closing because a reproducible example was never submitted. If you can still provide one (and this issue is still active), please reopen it.

**Closed by willeastcott** 2019-12-26 01:22 UTC
