### ISSUE TITLE
Shadow pass recompiles unnecessarily when adding entities at runtime

### ISSUE THREAD

**Issue by jbromberg** [playcanvas/engine#5538] opened 2023-08-02 20:56 UTC
I've noticed the shadow pass shader recompiles several times for identical entities when they're added at runtime. I've compared the code of the compiled shaders and they are identical.

It is my understanding that since the resulting shaders are identical they can be reused and don't need to be compiled again.

Here's a link to a simple repro project: https://playcanvas.com/project/1123191/overview/shadow-pass-recompiling

I'm using safari devtools to see the webgl programs. In this example project we add a single clone of the box to the scene after a short delay and we end up with 3 identical shadow pass shaders.

Here's a screenshot showing the 3 shaders (the duplicate ones are starred):
<img width="2287" alt="Screenshot 2023-08-02 at 3 37 15 PM" src="https://github.com/playcanvas/engine/assets/58891459/d0002510-9b7d-47d1-998f-36d41b8ec5f7">

**Comment by LeXXik** [comment] 2023-08-02 21:20
Might be related to #5512

**Comment by jbromberg** [comment] 2023-08-02 22:10
Let me see if updating fixes it

**Comment by LeXXik** [comment] 2023-08-03 11:12
I cannot reproduce this with 1.65.0.

**Comment by mvaligursky** [comment] 2023-08-03 11:20
Thanks @LeXXik . Closing this, but please re-open if there's some further issues.

**Closed by mvaligursky** 2023-08-03 11:20 UTC
Labels: bug, area: graphics
