### ISSUE TITLE
Cloning particles with mesh in component data.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#315] opened 2015-06-16 18:56 UTC
1. Create an entity.
2. Attach particles component.
3. Set particle mesh.
4. Clone from the script code.

It throws an exception.

**Comment by guycalledfrank** [comment] 2015-09-11 15:21
Not able to reproduce - perhaps was fixed in some commit.

**Closed by guycalledfrank** 2015-09-11 15:21 UTC
Labels: bug
