### ISSUE TITLE
Downscale cubemap texture if resolution is over supported.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#427] opened 2015-11-03 15:11 UTC
If `MAX_CUBE_MAP_TEXTURE_SIZE` is below the texture size that is set as frame, then we need to downscale that texture before setting as a face.

**Comment by willeastcott** [comment] 2016-06-28 12:35
@guycalledfrank Is this already fixed? 

https://github.com/playcanvas/engine/blob/master/src/graphics/device.js#L1025

Can you verify?

**Comment by Maksims** [comment] 2016-06-28 13:17
Noticed that on @daredevildave mac laptop, even 1024 cubemaps had only quarter (512) part textured, rest was black. Looks like partial support of it.

**Comment by guycalledfrank** [comment] 2016-06-29 12:35
Can't reproduce - existing code works if trying to force low maximum cubemap resolution.

**Comment by Maksims** [comment] 2016-06-30 11:19
It seems that webglreport for `Max Cube Map Texture Size` is larger that is actually supported. We have device that has only top left quarter of texture visible, but rest is black.
So it might be that opengl reports one resolution, but reality is different. So we perhaps need to make small test of that to detect this behaviour?

**Comment by guycalledfrank** [comment] 2016-06-30 18:14
Sounds like a driver bug to me. Not sure how to detect this behaviour quickly without actually creating a big texture (can cost some ms) and reading it back.

**Comment by willeastcott** [comment] 2016-06-30 18:50
Sounds like a browser/driver bug, so closing... Feel free to log as a bug on any relevant browser project.

**Comment by Maksims** [comment] 2016-06-30 22:54
Regardless of a source of issue, similarly to float and half texture format precision inconsistencies, if we can test for this and implement a workaround to ensure that users get appropriate cubemap scaling.
For developer's point of view - issue is on our side. If we can solve it, then we shall better do so.
This is motivated by recent forum post of a developer who found many devices having inconsistent cubemap renderings with specifically that issue.

**Comment by willeastcott** [comment] 2018-03-04 18:14
Closing due to lack of activity. Also, there are a million things we could test to check against broken WebGL implementations, but we have to draw a line somewhere. I'm all for posting bugs against browser projects for this kind of thing though. For that, I'd need: device, OS version, browser and browser version. Plus a cubemap asset that triggers the problem.

**Closed by willeastcott** 2018-03-04 18:14 UTC
Labels: bug
