### ISSUE TITLE
Empty scene with no lights fails to render

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#727] opened 2016-09-06 10:48 UTC
There is weird behaviour in Editor where scene with single model, no lights and no grid (in editor settings set grid to 0,0), will print some webgl warnings to console, and will not render entity until it is selected, or light is enabled.

https://playcanvas.com/editor/scene/456773

**Comment by guycalledfrank** [comment] 2016-09-07 16:17
This error can be related to the grid implementation (attempts to render something when divisions = 0?) given that it's not reproducible in Launch. Grid is not part of the engine, so I'm not quite sure how it's implemented.

**Comment by Maksims** [comment] 2016-09-07 17:08
Will debug it in Editor then.

**Comment by willeastcott** [comment] 2017-12-10 07:42
I can't reproduce this so I'm closing it.

**Closed by willeastcott** 2017-12-10 07:42 UTC
Labels: bug
