### ISSUE TITLE
Black line artefacts in Clustered Area Lights demo with Gloss 1 and Metalness 0

### ISSUE THREAD

**Issue by cognitiveplus** [playcanvas/engine#6337] opened 2024-05-04 12:05 UTC
Black line artefacts in [Clustered Area Lights](https://playcanvas.github.io/#/graphics/clustered-area-lights) demo appearing only with Gloss = 1 and Metalness = 0.
Macbook Air M1, Chrome / Safari
Both WebGL and WebGPU
16.5 Safari / Ventura 13.4

Video: https://github.com/playcanvas/engine/assets/5297578/c243a772-816e-48ab-9fb2-27ce3f3d686f

<img width="1280" alt="Screenshot 2024-05-04 at 15 59 44" src="https://github.com/playcanvas/engine/assets/5297578/3691393a-1b4f-4d55-876e-e2edc8162ea2">

**Comment by mvaligursky** [comment] 2024-05-07 07:49
possibly a duplicate of https://github.com/playcanvas/engine/issues/5116

**Comment by mvaligursky** [comment] 2024-10-09 10:43
Closing as I can no longer reproduce it. 
Even if I could, it seems https://github.com/playcanvas/engine/pull/7015 fixes multiple issues like this exactly, so it's likely fixing this too.

**Closed by mvaligursky** 2024-10-09 10:43 UTC
Labels: bug, area: graphics
