### ISSUE TITLE
skinning doesn't work with low bone limit and no bone texture support

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#518] opened 2016-02-16 15:23 UTC
If there is no bone texture support and skin splitting is required the skinning doesn't work properly (deformed).

To try this add these lines to Doom 3 Gangnam style or other project with skinned characters.

```
app.graphicsDevice.supportsBoneTextures = false;
app.graphicsDevice.boneLimit = 20;
```

**Comment by willeastcott** [comment] 2018-03-05 05:32
I just verified that the skin splitting does work. I suspect maybe you executed those lines after the model JSON has been parsed. To see the skin partitioner work, just have the texture_float extension return null and set the max vertex uniforms to 128. Then you'll get a bone limit of about 21. And it does actually work. The problem is that the engine has changed how it handles material mappings in the last few years. The skin partitioner does handle the mappings when they are passed in as a parameter. However, these days, the call has been changed to pass null. So materials are incorrectly assigned. And the extra mesh instances generated from the split simply get the default material:

![image](https://user-images.githubusercontent.com/697563/36958761-f2e814be-1ff2-11e8-9194-1b78a2b545a2.png)

The current skin splitter is really bad for another reason too. It manipulates the source JSON model format. It doesn't split the runtime format. This mean that if you load a glTF skinned model, say, the skin partitioner cannot split it.

I'm wondering if we should consider ripping it out and falling back to CPU skinning where necessary. I mean, we already have a CPU morphing path.

**Comment by mvaligursky** [comment] 2021-09-14 17:29
Another option here would be to fallback on the RGBA8/16 textures to store matrices. It would be lots more texture samples to get 4x3 matrix of floats, but should still be faster than CPU skinning.

These are the stats on vertex texture sampling support from about a year ago when webglstats still worked.
vertex texture reads: 4: 97.7%, 8: 79.9%, 16: 67.0%

**Comment by willeastcott** [comment] 2021-09-14 17:33
Wow, that's a cool idea, @mvaligursky. Deleting all that skin partitioning code from the engine would be great.

**Comment by mvaligursky** [comment] 2021-09-28 12:30
are we ok to drop support for up to 2% of devices (based on stats from a year ago) and do this? Or would we still need to do some backup CPU skinning or similar.

**Comment by willeastcott** [comment] 2021-10-03 22:04
This is a really difficult question to answer. On the one hand, I've always preferred we ensure the engine's core feature set runs on a minimum WebGL 1.0 spec. See [webgl.min_capability_mode](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API#gecko_notes). However, the skin splitting path is clearly broken at the moment, and I'm not aware of anybody complaining. I'm really torn, TBH!

**Comment by mvaligursky** [comment] 2023-06-01 10:46
Latest stats (1 Jun 2023) based on web3dsurvey.com

**WebGL2 support**: 97.61%

<img width="529" alt="Screenshot 2023-06-01 at 11 45 38" src="https://github.com/playcanvas/engine/assets/59932779/d18989b5-7df8-482a-9a81-e8cdff41998c">


**MAX_VERTEX_TEXTURE_IMAGE_UNITS:**
WebGL1, 4 vertex textures: 99.91% (android: 99.55%, Chromium, iOS, MacOS, Windows: 100%) 
WebGl2, 4 vertex textures: 100%

**OES_texture_float:**
WebGL1: 95.72% (android: 72.65%, Chromium: 94.6%, iOS: 99.96%, MacOS: 99.97%, Windows: 99.95%)
WebGl2: 100%

So out of about 2.4% of devices that support only WebGL1, about 4.3% does not support float textures, which is 1% of the whole market.

**Comment by willeastcott** [comment] 2023-06-01 23:14
Don't you mean 0.1%? 😄 

Yeah, I think we can just close this now and rip out that skin split stuff.

**Closed** 2024-03-19 16:24 UTC
Labels: bug, area: graphics
