### ISSUE TITLE
Compound Collision Shapes

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#514] opened 2016-02-03 23:52 UTC
We should add support for compound collision shapes.

I suggest that we combine all collision components on an entity with a rigidbody component and all of its descendants into a compound collision shape.

**Comment by Maksims** [comment] 2016-02-04 11:53
Duplicate of https://github.com/playcanvas/engine/issues/479

**Closed by Maksims** 2016-02-04 11:53 UTC
Labels: feature request
